"""
Generyczne nazwy składników do konsolidacji bazy produktów.
Kolejność ma znaczenie: bardziej specyficzne (2-słowowe) przed ogólnymi.
Skrypt szuka każdego keyword w nazwie produktu (case-insensitive)
i grupuje pasujące produkty pod tę nazwę.
"""

PRODUCT_KEYWORDS = [

    # ── MIĘSO ─────────────────────────────────────────────────────────────────
    "Filet z kurczaka",
    "Pierś z kurczaka",
    "Udo z kurczaka",
    "Podudzie z kurczaka",
    "Skrzydełka z kurczaka",
    "Mięso mielone wołowe",
    "Mięso mielone wieprzowe",
    "Mięso mielone drobiowe",
    "Mięso mielone",
    "Polędwiczka wieprzowa",
    "Polędwiczka z indyka",
    "Schab wieprzowy",
    "Karkówka wieprzowa",
    "Boczek wieprzowy",
    "Żeberka wieprzowe",
    "Łopatka wieprzowa",
    "Golonka wieprzowa",
    "Szynka wieprzowa",
    "Antrykot wołowy",
    "Rostbef wołowy",
    "Polędwica wołowa",
    "Udziec wołowy",
    "Kurczak",
    "Indyk",
    "Kaczka",
    "Gęś",
    "Królik",
    "Wołowina",
    "Wieprzowina",
    "Cielęcina",
    "Jagnięcina",
    "Boczek",
    "Szynka",
    "Kiełbasa",
    "Kabanosy",
    "Parówki",
    "Pasztet",
    "Mielonka",
    "Wędlina",

    # ── RYBY I OWOCE MORZA ────────────────────────────────────────────────────
    "Filet z łososia",
    "Filet z dorsza",
    "Filet z pstrąga",
    "Łosoś wędzony",
    "Łosoś",
    "Dorsz",
    "Pstrąg",
    "Tuńczyk",
    "Makrela",
    "Śledź",
    "Sardynki",
    "Szproty",
    "Mintaj",
    "Morszczuk",
    "Panga",
    "Krewetki",
    "Małże",
    "Kalmary",
    "Ośmiornica",

    # ── NABIAŁ ────────────────────────────────────────────────────────────────
    "Ser parmezan",
    "Ser feta",
    "Ser mozzarella",
    "Ser ricotta",
    "Ser mascarpone",
    "Ser camembert",
    "Ser brie",
    "Ser cheddar",
    "Ser gouda",
    "Ser żółty",
    "Ser kozi",
    "Ser twarogowy",
    "Ser",
    "Mozzarella",
    "Parmezan",
    "Feta",
    "Ricotta",
    "Mascarpone",
    "Camembert",
    "Twaróg",
    "Serek wiejski",
    "Serek twarogowy",
    "Serek kremowy",
    "Serek",
    "Jogurt naturalny",
    "Jogurt grecki",
    "Jogurt",
    "Kefir",
    "Maślanka",
    "Śmietana 30%",
    "Śmietana 18%",
    "Śmietana 12%",
    "Śmietana",
    "Śmietanka",
    "Mleko 3,2%",
    "Mleko 2%",
    "Mleko kokosowe",
    "Mleko owsiane",
    "Mleko migdałowe",
    "Mleko",
    "Masło",
    "Margaryna",
    "Ghee",
    "Ayran",

    # ── JAJKA ─────────────────────────────────────────────────────────────────
    "Jajko",

    # ── MAKARON ───────────────────────────────────────────────────────────────
    "Makaron ryżowy",
    "Makaron pełnoziarnisty",
    "Makaron",
    "Lasagne",
    "Gnocchi",
    "Tortellini",

    # ── RYŻ ───────────────────────────────────────────────────────────────────
    "Ryż basmati",
    "Ryż jaśminowy",
    "Ryż brązowy",
    "Ryż do sushi",
    "Ryż",

    # ── KASZE ─────────────────────────────────────────────────────────────────
    "Kasza gryczana",
    "Kasza jaglana",
    "Kasza bulgur",
    "Kasza kuskus",
    "Kasza orkiszowa",
    "Kasza",
    "Kuskus",
    "Quinoa",
    "Amarantus",

    # ── MĄKA I SKROBIA ────────────────────────────────────────────────────────
    "Mąka pszenna",
    "Mąka orkiszowa",
    "Mąka gryczana",
    "Mąka kukurydziana",
    "Mąka migdałowa",
    "Mąka owsiana",
    "Mąka ryżowa",
    "Mąka",
    "Skrobia ziemniaczana",
    "Skrobia kukurydziana",
    "Skrobia",
    "Bułka tarta",

    # ── PŁATKI I MUSLI ────────────────────────────────────────────────────────
    "Płatki owsiane",
    "Płatki kukurydziane",
    "Płatki ryżowe",
    "Płatki jaglane",
    "Płatki żytnie",
    "Płatki",
    "Musli",
    "Granola",
    "Otręby",

    # ── CHLEB I PIECZYWO ──────────────────────────────────────────────────────
    "Chleb żytni",
    "Chleb pszenny",
    "Chleb graham",
    "Chleb",
    "Bagietka",
    "Bułka",
    "Tortilla",
    "Naleśnik",
    "Pierogi",

    # ── WARZYWA ───────────────────────────────────────────────────────────────
    "Pomidor suszony",
    "Pomidory w puszce",
    "Pomidory krojone",
    "Koncentrat pomidorowy",
    "Pomidor",
    "Papryka czerwona",
    "Papryka żółta",
    "Papryka zielona",
    "Papryka",
    "Cebula czerwona",
    "Cebula",
    "Czosnek",
    "Marchew",
    "Seler naciowy",
    "Seler",
    "Por",
    "Ziemniak",
    "Batat",
    "Dynia",
    "Cukinia",
    "Bakłażan",
    "Brokuł",
    "Kalafior",
    "Kapusta biała",
    "Kapusta czerwona",
    "Kapusta kiszona",
    "Kapusta pekińska",
    "Kapusta",
    "Szpinak",
    "Jarmuż",
    "Rukola",
    "Sałata",
    "Ogórek",
    "Rzodkiewka",
    "Burak",
    "Kukurydza",
    "Groszek",
    "Fasola szparagowa",
    "Natka pietruszki",
    "Pietruszka",
    "Szparagi",
    "Pieczarka",
    "Grzyb",
    "Podgrzybek",
    "Kurka",
    "Boczniak",
    "Szpinak baby",
    "Kiełki",
    "Jarmuż",
    "Szczypiorek",
    "Koperek",

    # ── OWOCE ─────────────────────────────────────────────────────────────────
    "Ananas",
    "Arbuz",
    "Awokado",
    "Banan",
    "Borówka",
    "Brzoskwinia",
    "Cytryna",
    "Czarna porzeczka",
    "Czerwona porzeczka",
    "Daktyl",
    "Figa",
    "Grapefruit",
    "Gruszka",
    "Jabłko",
    "Jagody",
    "Kiwi",
    "Malina",
    "Mandarynka",
    "Mango",
    "Marakuja",
    "Melon",
    "Morela",
    "Pomarańcza",
    "Rabarbar",
    "Śliwka",
    "Truskawka",
    "Winogrono",
    "Wiśnia",
    "Żurawina suszona",
    "Żurawina",
    "Limonka",

    # ── STRĄCZKOWE ────────────────────────────────────────────────────────────
    "Ciecierzyca",
    "Soczewica czerwona",
    "Soczewica zielona",
    "Soczewica",
    "Fasola biała",
    "Fasola czerwona",
    "Fasola czarna",
    "Fasola",
    "Groch",
    "Bób",
    "Edamame",
    "Soja",
    "Tofu",
    "Tempeh",

    # ── ORZECHY I NASIONA ─────────────────────────────────────────────────────
    "Orzechy włoskie",
    "Orzechy nerkowca",
    "Orzechy laskowe",
    "Orzechy ziemne",
    "Orzechy pekan",
    "Orzechy",
    "Migdały",
    "Pistacje",
    "Nasiona chia",
    "Nasiona konopi",
    "Siemię lniane",
    "Sezam",
    "Słonecznik",
    "Pestki dyni",
    "Mak",
    "Rodzynki",
    "Żurawina suszona",
    "Daktyle",
    "Figi suszone",
    "Śliwki suszone",
    "Morele suszone",

    # ── OLEJE I TŁUSZCZE ──────────────────────────────────────────────────────
    "Oliwa z oliwek",
    "Olej kokosowy",
    "Olej rzepakowy",
    "Olej słonecznikowy",
    "Olej sezamowy",
    "Olej lniany",
    "Olej",
    "Oliwa",

    # ── SOSY I PRZETWORY ──────────────────────────────────────────────────────
    "Sos sojowy",
    "Sos worcestershire",
    "Sos rybny",
    "Sos tabasco",
    "Passata pomidorowa",
    "Passata",
    "Pesto",
    "Majonez",
    "Musztarda",
    "Ketchup",
    "Ocet balsamiczny",
    "Ocet jabłkowy",
    "Ocet",
    "Bulion drobiowy",
    "Bulion warzywny",
    "Bulion wołowy",
    "Bulion",
    "Rosół",
    "Dżem",
    "Miód",
    "Syrop klonowy",
    "Oliwki",
    "Kapary",
    "Korniszony",
    "Ogórek kiszony",
    "Ogórek konserwowy",
    "Tahini",
    "Hummus",
    "Przecier pomidorowy",

    # ── PRODUKTY SYPKIE / SŁODZĄCE ────────────────────────────────────────────
    "Cukier trzcinowy",
    "Cukier",
    "Erytrytol",
    "Stewia",
    "Melasa",
    "Kakao",
    "Czekolada gorzka",
    "Czekolada",
    "Wiórki kokosowe",
    "Kokos",

    # ── PIEKARNIA / INNE ──────────────────────────────────────────────────────
    "Drożdże",
    "Proszek do pieczenia",
    "Soda oczyszczona",
    "Żelatyna",
    "Tapioka",
    "Bułka tarta",

    # ── PRZYPRAWY (jednoskładnikowe) ──────────────────────────────────────────
    "Sól",
    "Pieprz czarny",
    "Pieprz biały",
    "Pieprz cayenne",
    "Pieprz",
    "Papryka słodka",
    "Papryka ostra",
    "Papryka wędzona",
    "Chili",
    "Kurkuma",
    "Cynamon",
    "Imbir mielony",
    "Imbir",
    "Czosnek granulowany",
    "Gałka muszkatołowa",
    "Goździki",
    "Kardamon",
    "Kminek",
    "Kmin rzymski",
    "Kolendra",
    "Kumin",
    "Anyż",
    "Ziele angielskie",
    "Liść laurowy",
    "Czarnuszka",
    "Sumak",

    # ── ZIOŁA ─────────────────────────────────────────────────────────────────
    "Bazylia",
    "Oregano",
    "Tymianek",
    "Rozmaryn",
    "Majeranek",
    "Cząber",
    "Lubczyk",
    "Estragon",
    "Mięta",
    "Natka pietruszki",

]
