"""increase product name to 255

Revision ID: 408d553cd2be
Revises: dea662a05cdc
Create Date: 2026-05-18 12:53:03.452354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408d553cd2be'
down_revision = 'dea662a05cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
