"""add category to recipes

Revision ID: 84130417ccbe
Revises: cf70b194ee20
Create Date: 2026-05-22 13:48:14.831319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84130417ccbe'
down_revision = 'cf70b194ee20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
