"""add source_url and macros_100g to recipes

Revision ID: cf70b194ee20
Revises: 408d553cd2be
Create Date: 2026-05-19 12:34:53.304723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf70b194ee20'
down_revision = '408d553cd2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('kcal_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs_100g', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('carbs_100g')
        batch_op.drop_column('fat_100g')
        batch_op.drop_column('protein_100g')
        batch_op.drop_column('kcal_100g')
        batch_op.drop_column('source_url')

    # ### end Alembic commands ###
