"""add household_members and member_id to meal_plans

Revision ID: db1cb04ca232
Revises: 65d1339e1de5
Create Date: 2026-05-15 16:25:13.739499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1cb04ca232'
down_revision = '65d1339e1de5'
branch_labels = None
depends_on = None


def _meal_plan_unique_constraints(bind):
    return {c['name'] for c in sa.inspect(bind).get_unique_constraints('meal_plans')}


def _meal_plan_columns(bind):
    return {c['name'] for c in sa.inspect(bind).get_columns('meal_plans')}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('activity', sa.Float(), nullable=True),
    sa.Column('goal', sa.String(length=20), nullable=True),
    sa.Column('macro_kcal', sa.Integer(), nullable=True),
    sa.Column('macro_protein', sa.Integer(), nullable=True),
    sa.Column('macro_fat', sa.Integer(), nullable=True),
    sa.Column('macro_carbs', sa.Integer(), nullable=True),
    sa.Column('macro_goal_label', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed: utwórz primary member dla każdego istniejącego użytkownika
    op.execute("""
        INSERT INTO household_members (user_id, name, is_primary)
        SELECT id, 'Ja', TRUE FROM users
    """)

    bind = op.get_bind()
    columns = _meal_plan_columns(bind)
    constraints = _meal_plan_unique_constraints(bind)

    # Fresh DBs never got user_id on meal_plans — add it before member_id work.
    if 'user_id' not in columns:
        with op.batch_alter_table('meal_plans', schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(
                'fk_meal_plans_user_id', 'users', ['user_id'], ['id']
            )
        op.execute("""
            UPDATE meal_plans
            SET user_id = (SELECT id FROM users ORDER BY id LIMIT 1)
            WHERE user_id IS NULL
        """)
        with op.batch_alter_table('meal_plans', schema=None) as batch_op:
            batch_op.alter_column('user_id', nullable=False)

    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=True))
        for name in ('unique_user_date_position', 'unique_date_position'):
            if name in constraints:
                batch_op.drop_constraint(name, type_='unique')
                break
        batch_op.create_foreign_key(None, 'household_members', ['member_id'], ['id'])

    # Backfill: przypisz istniejące posiłki do primary membera danego użytkownika
    op.execute("""
        UPDATE meal_plans mp
        SET member_id = hm.id
        FROM household_members hm
        WHERE hm.user_id = mp.user_id AND hm.is_primary = TRUE
    """)

    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_member_date_position', ['member_id', 'date', 'position'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_member_date_position', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_user_date_position'), ['user_id', 'date', 'position'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('member_id')

    op.drop_table('household_members')
    # ### end Alembic commands ###
