"""add macro fields to product

Revision ID: e035c31ce8de
Revises: 913247cf2cef
Create Date: 2026-05-13 13:30:00.047147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e035c31ce8de'
down_revision = '913247cf2cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kcal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('carbs')
        batch_op.drop_column('fat')
        batch_op.drop_column('protein')
        batch_op.drop_column('kcal')

    # ### end Alembic commands ###
