"""add lang to products and recipes

Revision ID: eb979d9ec1a2
Revises: 84130417ccbe
Create Date: 2026-05-22 14:42:28.617061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb979d9ec1a2'
down_revision = '84130417ccbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang', sa.String(length=5), nullable=True))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('lang')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('lang')

    # ### end Alembic commands ###
