export type ExpenseTypeMeta = {
  key: string;
  label: string;
  emoji: string;
  gradient: string;
};

export type DrinkKey = "kawa" | "herbata" | "napoje" | "woda" | "sodaStream";

export type DrinkTypeMeta = {
  key: DrinkKey;
  emoji: string;
  gradient: string;
};

export const OTHER_TYPES: ExpenseTypeMeta[] = [
  { key: "czynsz", label: "Czynsz", emoji: "🏠", gradient: "linear-gradient(135deg,#1a1020,#3a2050)" },
  { key: "prad", label: "Prąd", emoji: "⚡", gradient: "linear-gradient(135deg,#1a1800,#3a3800)" },
  { key: "gaz_oplata", label: "Gaz", emoji: "🔥", gradient: "linear-gradient(135deg,#1a0a00,#4a2000)" },
  { key: "media", label: "Media", emoji: "📡", gradient: "linear-gradient(135deg,#001020,#002050)" },
  { key: "ogrzewanie", label: "Ogrzewanie", emoji: "🌡️", gradient: "linear-gradient(135deg,#200a00,#502000)" },
  { key: "kredyt", label: "Kredyt", emoji: "💳", gradient: "linear-gradient(135deg,#001a10,#004030)" },
  { key: "dziecko", label: "Dziecko", emoji: "🧸", gradient: "linear-gradient(135deg,#2a1020,#5a2040)" },
  { key: "zwierze", label: "Zwierzę", emoji: "🐾", gradient: "linear-gradient(135deg,#1a1a0a,#3a3a10)" },
  { key: "lekarze", label: "Lekarze i leki", emoji: "🏥", gradient: "linear-gradient(135deg,#0a1a10,#0a3a20)" },
  { key: "paliwo", label: "Paliwo", emoji: "⛽", gradient: "linear-gradient(135deg,#2a0a0a,#5a1a1a)" },
  { key: "pranie", label: "Pranie", emoji: "🫧", gradient: "linear-gradient(135deg,#0a2040,#1a5080)" },
  { key: "zmywanie", label: "Zmywanie", emoji: "🍽️", gradient: "linear-gradient(135deg,#1a2a0a,#3a5a1a)" },
  { key: "sprzatan", label: "Sprzątanie", emoji: "🧹", gradient: "linear-gradient(135deg,#2a1a0a,#5a3a1a)" },
  { key: "higiena", label: "Higiena", emoji: "🪥", gradient: "linear-gradient(135deg,#1a0a2a,#3a1a5a)" },
  { key: "biurowe", label: "Art. biurowe", emoji: "📎", gradient: "linear-gradient(135deg,#0a1a2a,#1a3a4a)" },
];

/** Household expense keys shared across profiles (one budget per household). */
export const SHARED_KEYS = new Set([
  "czynsz",
  "prad",
  "gaz_oplata",
  "media",
  "ogrzewanie",
  "dziecko",
  "zwierze",
  "pranie",
  "zmywanie",
  "sprzatan",
]);

export const OTHER_DEFAULTS: Record<string, Record<string, unknown>> = {
  papier: { enabled: false, monthlyAmount: "", dailyRolls: "0.5", pkgPrice: "", rollsPerPkg: "8" },
  pranie: {
    enabled: false,
    monthlyAmount: "",
    washesPerWeek: "5",
    detergentType: "proszek",
    proszekPerWash: "75",
    proszekPkgKg: "3",
    proszekPkgPrice: "",
    plynPerWash: "35",
    plynPkgL: "1.5",
    plynPkgPrice: "",
    kapsulkiPerPkg: "30",
    kapsulkiPkgPrice: "",
    plukanie: false,
    plukaniePerWash: "25",
    plukanieL: "1",
    plukaniePkgPrice: "",
  },
  zmywanie: {
    enabled: false,
    monthlyAmount: "",
    useReczne: false,
    useZmywarka: false,
    pkgDuration: "30",
    durationUnit: "dni",
    pkgPrice: "",
    usesPerWeek: "7",
    kapsPerPkg: "30",
    kapsulkiPkgPrice: "",
  },
  sprzatan: { enabled: false, monthlyAmount: "", bagsPerWeek: "", bagsPerPkg: "20", bagsPkgPrice: "", cleaningItems: [] },
  higiena: {
    enabled: false,
    monthlyAmount: "",
    zbRazDzien: "2",
    zbPastaG: "1",
    zbTubkaMl: "75",
    zbTubkaPrice: "",
    zbSzczetokaPrice: "",
    wlRazW: "3",
    wlSzampon: false,
    wlSzamponWyc: "2",
    wlSzamponMl: "400",
    wlSzamponPrice: "",
    wlOdzywka: false,
    wlOdzywkaWyc: "1",
    wlOdzywkaMl: "300",
    wlOdzywkaPrice: "",
    kapRazW: "7",
    kapZel: false,
    kapZelWyc: "3",
    kapZelMl: "400",
    kapZelPrice: "",
    kapMydlo: false,
    kapMydloG: "90",
    kapMydloPrice: "",
    inneItems: [],
    papierE: false,
    papierDailyRolls: "",
    papierRollsPerPkg: "",
    papierPkgPrice: "",
  },
  dziecko: {
    enabled: false,
    monthlyAmount: "",
    przedszkoleE: false,
    przedszkole: "",
    obiadE: false,
    obiad: "",
    zajeciaE: false,
    zajecia: "",
    korepetycjeE: false,
    korepetycje: "",
    materialyE: false,
    materialy: "",
    dojazdyE: false,
    dojazdy: "",
    odziezdE: false,
    odziez: "",
    kieszonkoweE: false,
    kieszonkowe: "",
    zabawkiE: false,
    zabawki: "",
    kosmetykiE: false,
    kosmetyki: "",
    pieluchyEnabled: false,
    pieluchyPerDay: "5",
    pieluchyPerPkg: "50",
    pieluchyPrice: "",
    mlekoEnabled: false,
    mlekoPerDay: "5",
    mlekoPkgScoops: "30",
    mlekoPrice: "",
    extraItems: [],
  },
  zwierze: {
    enabled: false,
    monthlyAmount: "",
    suchaE: false,
    suchaG: "50",
    suchaPkgG: "2000",
    suchaPrice: "",
    mokraE: false,
    mokraSzt: "1",
    mokraGram: "400",
    mokraPrice: "",
    zwierekE: false,
    zwierekDni: "7",
    zwierekL: "3",
    zwierekPkgL: "5",
    zwierekPrice: "",
    wetE: false,
    wet: "",
    pielegnacjaE: false,
    pielegnacja: "",
    akcesoriaE: false,
    akcesoria: "",
    extraItems: [],
  },
  lekarze: { enabled: false, monthlyAmount: "", wizyty: "", leki: "" },
  biurowe: {
    enabled: false,
    monthlyAmount: "",
    papierA4E: false,
    papierA4: "",
    tuszE: false,
    tusz: "",
    notatnikE: false,
    notatnik: "",
    dlugopisyE: false,
    dlugopisy: "",
    extraItems: [],
  },
  paliwo: { enabled: false, monthlyAmount: "", fuelType: "diesel", kmPerDay: "", consumption: "", fuelPrice: "", fetchedPrices: {} },
  czynsz: { enabled: false, monthlyAmount: "" },
  prad: { enabled: false, monthlyAmount: "" },
  gaz_oplata: { enabled: false, monthlyAmount: "" },
  media: { enabled: false, monthlyAmount: "", internetE: false, internet: "", telefonE: false, telefon: "", tvE: false, tv: "" },
  ogrzewanie: { enabled: false, monthlyAmount: "" },
  kredyt: { enabled: false, monthlyAmount: "" },
};

export const DRINK_TYPES: DrinkTypeMeta[] = [
  { key: "kawa", emoji: "☕", gradient: "linear-gradient(135deg,#2d1000,#7a3800)" },
  { key: "herbata", emoji: "🍵", gradient: "linear-gradient(135deg,#0a1f0a,#1a5a1a)" },
  { key: "napoje", emoji: "🥤", gradient: "linear-gradient(135deg,#0a1040,#1a3a8a)" },
  { key: "woda", emoji: "💧", gradient: "linear-gradient(135deg,#001828,#006080)" },
  { key: "sodaStream", emoji: "🫧", gradient: "linear-gradient(135deg,#100a30,#3a0a6a)" },
];

export const DRINKS_DEFAULTS: Record<string, Record<string, unknown>> = {
  kawa: {
    enabled: false,
    cupsPerDay: 2,
    spoonsPerCup: 2,
    pkgG: 200,
    pkgPrice: "",
    sugarType: null,
    sugarSpoons: 1,
    milkType: null,
    milkMlPerCup: "",
    milkPkgMl: "",
    milkPrice: "",
  },
  herbata: {
    enabled: false,
    cupsPerDay: 2,
    sachetPerPkg: 20,
    pkgPrice: "",
    sugarType: null,
    sugarSpoons: 1,
    milkType: null,
    milkMlPerCup: "",
    milkPkgMl: "",
    milkPrice: "",
  },
  napoje: { enabled: false, litersPerDay: 1, pkgL: 1.5, pkgPrice: "" },
  woda: { enabled: false, litersPerDay: 2, pkgL: 1.5, pkgPrice: "" },
  sodaStream: {
    enabled: false,
    litersPerDay: 1,
    syrupMl: 440,
    syrupPrice: "",
    mlPer1L: 25,
    cylinderDays: "",
    cylinderCost: "",
  },
};
