import React, { createContext, useContext, useState } from 'react';

const T = {
  pl: {
    // App/Nav
    loading: 'Ładowanie…',
    tab_macro: 'Kalkulator Makro',
    tab_calendar: 'Planer Posiłków',
    tab_recipes: 'Przepisy',
    tab_products: 'Produkty',
    tab_summary: 'Wydatki',
    tab_export: 'Eksport',
    logout: 'Wyloguj',
    profile: 'Profil',
    account: 'Konto',
    // Profile modal
    my_profile: 'Mój profil',
    delete_account: 'Usuń konto',
    delete_confirm: 'Czy na pewno chcesz usunąć swoje konto? Wszystkie dane zostaną trwale usunięte. Tej operacji nie można cofnąć.',
    close: 'Zamknij',
    deleting: 'Usuwanie…',
    show_tutorial: 'Pokaż samouczek',
    // Login
    subtitle_login: 'Zaloguj się do swojego konta',
    subtitle_register: 'Utwórz nowe konto Ontrack',
    login_tagline: 'Planuj posiłki. Trzymaj budżet.',
    login_tagline_desc: 'Kalendarz tygodniowy, przepisy z kosztami i makroskładnikami oraz produkty z aktualnymi cenami ze sklepów.',
    login_feature_calendar: 'Tygodniowy kalendarz posiłków dla całej rodziny',
    login_feature_recipes: 'Przepisy z kosztem porcji i makroskładnikami',
    login_feature_budget: 'Produkty z cenami z Aldi, Auchan i Biedronki',
    login_value_prop: '450+ produktów i 65+ przepisów od razu po rejestracji',
    login_tab_login: 'Logowanie',
    login_tab_register: 'Rejestracja',
    login_username_lbl: 'NAZWA UŻYTKOWNIKA',
    login_password_lbl: 'HASŁO',
    login_busy_login: 'Logowanie…',
    login_busy_register: 'Tworzenie konta…',
    google_btn: 'Kontynuuj przez Google',
    login_username_ph: 'np. janek123',
    login_email_ph: 'Adres e-mail',
    login_password_ph: 'Min. 8 znaków',
    login_submit: 'Zaloguj się',
    login_register_submit: 'Utwórz konto',
    login_or: 'lub',
    login_switch_register: 'Nie masz konta? Zarejestruj się',
    login_switch_login: 'Masz już konto? Zaloguj się',
    err_login_failed: 'Nieprawidłowa nazwa użytkownika lub hasło',
    err_register_failed: 'Rejestracja nie powiodła się — spróbuj ponownie',
    account_language: 'JĘZYK KONTA',
    // Calendar arrays
    slot_labels: ['Śniadanie', 'Drugie śniadanie', 'Obiad', 'Podwieczorek', 'Kolacja'],
    month_names: ['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'],
    day_short: ['Pon','Wt','Śr','Czw','Pt','Sob','Niedz'],
    day_full: ['Poniedziałek','Wtorek','Środa','Czwartek','Piątek','Sobota','Niedziela'],
    // Calendar UI
    how_to_title: 'Jak korzystać z kalendarza?',
    expand: 'Rozwiń',
    collapse: 'Zwiń',
    tpl_title: 'Stwórz szablon',
    your_tpls: 'Zapisane szablony',
    tpl_drag_hint: 'Przeciągnij przepisy z Przepisów na dni tygodnia, następnie nazwij i zapisz swój szablon. Wyczyść resetuje szablon.',
    tpl_name_ph: 'Nazwa szablonu (np. Tydzień fit)',
    save_tpl: 'Zapisz szablon',
    clear: 'Wyczyść',
    no_tpls: 'Brak zapisanych szablonów — utwórz pierwszy powyżej.',
    apply_from_mon: 'Zastosuj od poniedziałku:',
    apply: 'Zastosuj',
    meals_count: (n) => `${n} posiłków`,
    carousel_title: 'Przepisy',
    drag_to_cal: 'Przeciągnij na dzień w kalendarzu lub na szablon poniżej',
    no_recipes_cal: 'Brak przepisów',
    search_recipe_ph: 'Szukaj przepisu...',
    cat_all: 'Wszystkie',
    cat_breakfast: 'Śniadanie',
    cat_lunch: 'Obiad',
    cat_dinner: 'Kolacja',
    cat_snack: 'Snack',
    cat_dessert: 'Deser',
    err_load_recipes: 'Błąd ładowania przepisów',
    err_load_plan: 'Błąd ładowania planu',
    err_del_meal: 'Błąd usuwania posiłku',
    err_del_meals: 'Błąd usuwania posiłków',
    err_del_week: 'Błąd usuwania tygodnia',
    err_paste_day: 'Błąd wklejania dnia',
    err_paste_week: 'Błąd wklejania tygodnia',
    err_copy_day: 'Błąd kopiowania dnia',
    err_add_meal: 'Błąd dodawania posiłku',
    err_move_meal: 'Błąd przenoszenia posiłku',
    confirm_del_day: (n, d) => `Usunąć wszystkie ${n} posiłki z ${d}?`,
    confirm_del_week: (n) => `Usunąć wszystkie ${n} posiłki z tego tygodnia?`,
    toast_copy_day: (d) => `⧉ Skopiowano dzień ${d}`,
    toast_copy_week: '⧉ Tydzień skopiowany do schowka i edytora szablonu',
    clipboard_day: (d) => `Schowek: dzień ${d}`,
    clipboard_week: (d) => `Schowek: tydzień od ${d}`,
    clear_clipboard: '✕ wyczyść',
    paste_day_hint: 'kliknij ⎘ na innym dniu żeby wkleić',
    paste_week_hint: 'kliknij ⎘ przy innym tygodniu żeby wkleić',
    drag_day_title: 'Przeciągnij dzień',
    copy_day_title: 'Kopiuj dzień',
    paste_day_title: 'Wklej dzień',
    del_day_title: 'Usuń wszystkie posiłki tego dnia',
    copy_week_title: 'Kopiuj tydzień / załaduj do szablonu',
    paste_week_title: 'Wklej tydzień',
    del_week_title: 'Usuń cały tydzień',
    btn_grab: 'Chwyć',
    btn_copy: 'Kopiuj',
    btn_paste: 'Wklej',
    btn_delete: 'Usuń',
    btn_copied: 'Skopiowano',
    day_deleted_ok: 'Dzień usunięty',
    week_deleted_ok: 'Tydzień usunięty',
    btn_create_recipe: '+ Stwórz przepis',
    btn_create_template: '+ Stwórz szablon',
    btn_go_calendar: 'Idź do kalendarza',
    current_profile: 'Obecny profil',
    est_cost: 'szac. koszt',
    recipe_cost_lbl: 'Szac. koszt przepisu',
    currency: 'zł',
    macro_p: 'B',
    macro_f: 'T',
    macro_c: 'W',
    unit_pcs: 'szt',
    ht_meals_title: 'Planowanie posiłków',
    ht_meals_1: 'Chwyć przepis z "Przepisy" pod kalendarzem i przeciągnij na wybrany slot w dniu',
    ht_meals_2: 'Posiłek możesz przenieść między dniami przeciągając go za nazwę',
    ht_meals_3: 'Kliknij ✕ przy posiłku żeby go usunąć, lub "usuń" w nagłówku dnia żeby wyczyścić cały dzień',
    ht_copy_title: ' Kopiowanie dni i tygodni',
    ht_copy_1: '"Kopiuj" w nagłówku dnia kopiuje dzień do schowka',
    ht_copy_2: '"Wklej" w nagłówku dnia wkleja schowek na inny dzień',
    ht_copy_3: 'Przeciągaj dzień na inny dzień żeby skopiować go bezpośrednio',
    ht_copy_4: 'kopiuj, wklej lub usuń cały tydzień za pomocą przycisków po lewej stronie każdego wiersza',
    ht_tpl_title: ' Szablony tygodnia',
    ht_tpl_1: 'Kliknij "Kopiuj" obok tygodnia — załaduje posiłki do edytora szablonu poniżej',
    ht_tpl_2: 'W edytorze przeciągaj przepisy z "Przepisy" na dni tygodnia',
    ht_tpl_3: 'Wpisz nazwę i kliknij Zapisz szablon',
    ht_tpl_4: 'Szablon możesz zastosować na dowolny przyszły tydzień',
    ht_macro_title: ' Kolory makro w kalendarzu',
    ht_macro_1: 'Zapisz cele makro w zakładce "Kalkulator Makro" (kcal, białko, tłuszcze, węgle)',
    ht_macro_2: 'Pod każdym dniem z posiłkami pojawi się podsumowanie w formacie: aktualna / cel',
    ht_macro_3: 'Zielony - w granicach 10% celu · Żółty - 10–25% · Czerwony - powyżej 25% odchylenia',
    // Recipes
    add_recipe_title: 'Dodaj przepis',
    how_to_recipe: 'Jak dodać przepis?',
    format_title: 'Format tekstu:',
    fmt_1: 'Pierwsza linia - nazwa przepisu',
    fmt_1_rest: '— w pierwszej linii (obowiązkowo!)',
    fmt_2: 'Każdy składnik w osobnej linii',
    fmt_3: 'Podaj nazwę składnika i ilość z jednostką (g, ml, kg, l, łyżka, łyżeczka, szklanka…)',
    fmt_4: 'Możesz wkleić tekst ze strony z przepisem',
    ai_tip: 'Dodaj z AI - AI wyciągnie składniki za Ciebie i dopasuje do produktów w bazie, rozumiejąc kontekst i niestandardowe formaty.',
    regex_tip: 'Dodaj  - Nie wymaga działania przy standardowych formatach. Przy nietypowych wymaga sprawdzenia i poprawienia dopasowań, ale jest za darmo i bez limitu.',
    daily_limit: 'Limit: 2 dziennie.',
    example: 'Przykład:',
    remaining_ai: (n) => `Pozostało dziś wykorzystań AI: ${n}`,
    recipe_ph: 'Wklej lub wpisz przepis...\n\n══ NAZWA PRZEPISU ══  ← pierwsza linia!\nSkładnik 1 - ilość\nSkładnik 2 - ilość',
    parse_ai_btn: 'Dodaj z AI',
    parsing_ai: 'Gemini analizuje...',
    parse_regex_btn: 'Dodaj',
    recipe_name_lbl: 'Nazwa przepisu',
    ingredients_lbl: (m, total) => `Składniki — ${m}/${total} dopasowanych`,
    save_recipe: 'Zapisz przepis',
    back: 'Wróć',
    original_text_lbl: 'Oryginalny tekst przepisu - porównaj i ręcznie dołóż brakujące składniki',
    recipe_list_title: 'Lista przepisów',
    no_recipes_add: 'Brak przepisów — dodaj pierwszy!',
    col_product: 'Produkt',
    col_weight: 'Potrzebuje',
    col_cost: 'Koszt składników',
    info_section: 'Info',
    edit_notes: 'Edytuj',
    save_notes: 'Zapisz',
    cancel: 'Anuluj',
    no_notes: 'Brak notatek — kliknij Edytuj żeby dodać.',
    no_match_opt: '— brak dopasowania —',
    err_save_recipe: 'Błąd zapisywania przepisu',
    err_save_notes: 'Błąd zapisywania notatki',
    err_no_name: 'Brak nazwy przepisu',
    err_no_ingredients: 'Żaden składnik nie ma dopasowanego produktu',
    err_parse_regex: 'Nie udało się wyłapać składników — sprawdź format',
    err_gemini_not_configured: 'Parsowanie AI niedostępne — użyj «Dodaj bez AI»',
    err_gemini_busy: 'Gemini jest przeciążony — spróbuj za chwilę lub użyj «Dodaj bez AI»',
    ai_parse_unavailable: 'AI niedostępne na serwerze — użyj «Dodaj bez AI»',
    confirm_del_recipe: 'Usunąć przepis?',
    show_ingredients: 'Składniki',
    hide_ingredients: 'Zwiń',
    delete: 'Usuń',
    err_load_recipes_list: 'Błąd ładowania przepisów',
    // Products
    add_product_title: 'Dodaj produkt',
    basic_info: 'Podstawowe informacje',
    product_name_lbl: 'Nazwa produktu',
    product_name_ph: 'np. Jogurt naturalny',
    pkg_qty_lbl: 'Ilość w opakowaniu',
    unit_lbl: 'Jednostka',
    price_section: 'Cena',
    pkg_price_lbl: 'Cena opakowania (zł)',
    pkg_price_ph: 'np. 3.49',
    macro_auto_title: 'Makro i Kalorie dodawane automatycznie',
    macro_auto_desc: 'Po dodaniu produktu system pobierze wartości Kcal, Białka, Tłuszczów i Węglowodanów automatycznie z bazy Open Food Facts.',
    macro_edit_hint: 'Chcesz je zmienić? Kliknij Edytuj przy produkcie na liście poniżej.',
    add_product_btn: 'Dodaj produkt',
    import_title: 'Importuj ceny z paragonu lub pliku CSV / TXT',
    import_how_to: 'Jak korzystać z importu?',
    opt1_title: 'Opcja 1: Zdjęcie paragonu',
    opt1_s1: 'Wgraj zdjęcie JPG, PNG lub WEBP',
    opt1_s2: 'Kliknij Zastosuj AI - Gemini wyciągnie produkty i ceny',
    opt1_s3: 'Sprawdź dopasowania i kliknij Zastosuj',
    ai_daily_lim: 'Limit: 2 importy AI dziennie.',
    ai_rem: (n) => ` Pozostało: ${n}.`,
    opt2_title: 'Opcja 2: Plik CSV / TXT',
    opt2_fmt: 'Format:',
    opt2_s2: 'Wgraj plik i kliknij Zastosuj plik',
    no_lim: '✓ Bez limitu.',
    click_drag_file: 'Kliknij lub przeciągnij plik',
    file_types_hint: 'Opcja 1: JPG, PNG, WEBP - paragon (AI) | Opcja 2: TXT, CSV (darmowe)',
    click_change: 'Kliknij żeby wybrać inny plik',
    apply_ai_btn: ' Zastosuj przez AI (Gemini)',
    analyzing: ' Gemini analizuje...',
    apply_file_btn: ' Zastosuj plik (darmowe)',
    processing: ' Przetwarzam...',
    check_prices: 'Zaznacz produkty, sprawdź ceny i kliknij Zastosuj.',
    col_from_receipt: 'Z paragonu',
    col_qty: 'Ilość',
    col_pkg_price: 'Cena opak.',
    col_matched: 'Dopasowany produkt',
    col_new_price: 'Nowa cena',
    no_match_prod: 'Brak dopasowania',
    apply_changes: 'Zastosuj zmiany',
    import_review_hint_pre: 'Sprawdź dopasowania i uzupełnij dane. Zaznacz',
    import_review_hint_suf: 'dla warzyw, owoców i mięsa, podaj wtedy cenę za kg.',
    create_new_product_opt: '➕ Utwórz nowy produkt',
    create_new_product_label: 'Utwórz nowy produkt',
    import_new_product_hint_suf: ', a zostanie on dodany do listy Produkty.',
    price_per_pkg_suffix: '/ opak.',
    import_updated_n: (n) => `Zaktualizowano ${n}`,
    import_added_n: (n) => `Dodano ${n}`,
    import_done_suffix: 'produktów · Makro zaktualizowane',
    product_list_title: 'Lista produktów',
    col_name: 'Nazwa',
    col_kcal: 'Kcal/100g',
    col_macro: 'Makro / 100g',
    col_price: 'Cena',
    edit_btn: 'Edytuj',
    save_btn: 'Zapisz',
    del_btn: 'Usuń',
    confirm_del_product: 'Usunąć produkt?',
    no_products: 'Brak produktów',
    fetching_macro: ' Pobieranie Makro i Kalorii z Open Food Facts…',
    kcal_lbl: 'Kalorie (kcal/100g)',
    protein_lbl: 'Białko (g/100g)',
    fat_lbl: 'Tłuszcze (g/100g)',
    carbs_lbl: 'Węglowodany (g/100g)',
    auto_fill: ' Auto Uzupełnij',
    price_tip: (unit) => {
      const u = unit === 'szt' ? 'szt' : unit === 'ml' ? '100ml' : '100g';
      return ` Cena: wpisz ilość w opakowaniu i cenę za całe opakowanie — system przeliczy na zł/${u}.`;
    },
    auto_fill_tip: 'Auto Uzupełnij — pobiera Kcal i Makro automatycznie z bazy Open Food Facts na podstawie nazwy produktu.',
    err_fill_fields: 'Wypełnij wszystkie pola',
    err_not_found_off: (name) => `Nie znaleziono danych dla "${name}" — uzupełnij ręcznie`,
    err_off: 'Błąd połączenia z Open Food Facts',
    err_load_products: 'Błąd ładowania produktów',
    macro_updated_suffix: ' · Makro zaktualizowane automatycznie.',
    at_least_one: 'Zaznacz przynajmniej jeden produkt',
    // Summary
    summary_title: '📊 Podsumowanie zakupów',
    date_from: 'Od',
    date_to: 'Do',
    generate: 'Generuj',
    generating: 'Ładowanie...',
    shopping_list_title: 'Lista zakupów',
    col_total_weight: 'Łączna gramatura',
    col_exact_pkgs: 'Opakowania (dokładnie)',
    col_buy_pkgs: 'Opakowania (do kupienia)',
    col_price_per_pkg: 'Cena/opak.',
    col_total_cost: 'Koszt całkowity',
    summary_period: (s, e) => `Okres: ${s} — ${e}`,
    summary_prod_count: (n) => `Liczba produktów: ${n}`,
    total_cost_lbl: 'Łączny koszt zakupów',
    no_meals_range: 'Brak zaplanowanych posiłków w wybranym okresie',
    err_load_summary: 'Błąd ładowania podsumowania',
    err_select_range: 'Wybierz zakres dat',
    err_date_order: 'Data początkowa nie może być późniejsza niż końcowa',
    // Summary new
    this_week: 'Bieżący tydzień',
    this_month: 'Bieżący miesiąc',
    custom_period: 'Wybrany okres',
    week_templates_sum: 'Szablony tygodniowe',
    show_product_list: 'Rozwiń listę produktów',
    hide_product_list: 'Zwiń listę produktów',
    go_edit_hint: 'przejdź do Przepisów aby edytować',
    est_weekly_cost: 'Szacowany koszt tygodnia',
    no_tpl_summary: 'Brak szablonów. Utwórz je w Planerze Posiłków.',
    no_meals_period: 'Brak zaplanowanych posiłków w tym okresie',
    total_cost_lbl2: 'Łączny koszt',
    meals_n: (n) => `${n} posiłków`,
    monthly_label: 'Miesięcznie (zł)',
    check_data_label: 'Sprawdź czy dane są poprawne:',
    pkg_btn: 'W opak.',
    pkg_capacity_lbl: 'Pojemność opakowania',
    weight_btn_short: 'Na wagę',
    // Export
    export_generate_title: 'Generuj dokumenty',
    export_period_label: 'OKRES (WYDATKI I KALENDARZ)',
    export_who_label: 'KOGO UWZGLĘDNIAMY',
    export_btn_summary: 'Podsumowanie wydatków',
    export_btn_macro: 'Karta Makro',
    export_btn_calendar: 'Karta Kalendarza',
    export_btn_ingredients: 'Składniki przepisu',
    export_shopping_hint: 'Zaznacz dni — lista produktów z przepisów przeliczona na opakowania.',
    export_generate_list: 'Generuj listę zakupów',
    export_include_profiles: 'UWZGLĘDNIJ PROFILE',
    export_how_title: 'Jak działa eksport?',
    export_preview_title: 'Podgląd',
    export_no_meals: 'Brak zaplanowanych posiłków',
    food_label: 'Jedzenie',
    drinks_label: 'Napoje',
    by_weight_label: 'wagowo',
    sold_by_weight_label: 'Produkt sprzedawany na wagę',
    col_weight_used: 'Gram. użyta',
    col_pkg_size: 'Pojemność opak.',
    col_pcs: 'Szt.',
    col_price_per_pkg: 'Cena/opak.',
    col_in_stock: 'W zapasie',
    col_reduces_cost: 'zmniejsza koszt zakupy',
    col_shopping: 'zakupy',
    col_cost: 'koszt',
    click_to_edit_hint: 'kliknij aby edytować',
    stock_full: 'Całość',
    stock_part: 'Część',
    enter_amount_label: 'Podaj ile',
    search_product_ph: 'Szukaj produktu...',
    quantity_ph: 'ilość',
    add_btn: 'Dodaj',
    col_pkg_capacity: 'POJEMNOŚĆ OPAKOWANIA',
    col_price_opak_kg: 'CENA (OPAK/KG)',
    expenses_select_title: 'WYBIERZ WYDATKI KTÓRE CHCESZ SUMOWAĆ',
    expenses_shared: 'wspólne',
    expenses_total: 'Łącznie',
    exp_rent: 'Czynsz',
    exp_electricity: 'Prąd',
    exp_gas: 'Gaz',
    exp_utilities: 'Media',
    exp_heating: 'Ogrzewanie',
    exp_loan: 'Kredyt',
    exp_child: 'Dziecko',
    exp_pet: 'Zwierzę',
    exp_medical: 'Lekarze i leki',
    exp_fuel: 'Paliwo',
    exp_laundry: 'Pranie',
    exp_dishwashing: 'Zmywanie',
    exp_cleaning: 'Sprzątanie',
    exp_hygiene: 'Higiena',
    exp_office_supplies: 'Art. biurowe',
    dc_washes_per_week: 'Ilość prań / tydzień',
    dc_detergent: 'ŚRODEK PIORĄCY',
    dc_powder: 'Proszek', dc_liquid: 'Płyn', dc_capsules: 'Kapsułki',
    dc_grams_per_wash: 'Gramów na pranie',
    dc_pkg_capacity_kg: 'Pojemność op. (kg)',
    dc_pkg_capacity_l: 'Pojemność op. (l)',
    dc_pkg_capacity_ml: 'Pojemność op. (ml)',
    dc_pkg_price: 'Cena op. (zł)',
    dc_pkg_price_full: 'Cena opakowania (zł)',
    dc_fabric_softener: 'Płyn do płukania',
    dc_fabric_softener_section: 'PŁYN DO PŁUKANIA',
    dc_washes_per_pkg: 'Kapsułek w opakowaniu',
    dc_cups_per_day: 'Filiżanek dziennie',
    dc_sugar_type: 'Typ słodzidła',
    dc_spoons_per_cup: 'Łyżeczek na filiżankę',
    dc_milk_type: 'Mleko / śmietanka',
    dc_ml_per_cup: 'ml na filiżankę',
    dc_per_day: 'dziennie',
    dc_per_week: '/ tydzień',
    dc_days_label: (n) => `× ${n} dni`,
    dc_monthly: 'Miesięcznie (zł)',
    dc_liters_per_day: 'Litrów dziennie',
    dc_pkg_liters: 'Pojemność opakowania (l)',
    dc_soap_ml: 'Dozowania na pranie',
    dc_rinse_ml: 'ml płynu / pranie',
    dc_capsules_per_pkg: 'Kapsułek w opakowaniu',
    // DrinksCard — dodatkowe
    dc_rolls_per_day: 'Dzienne zużycie (rolki)',
    dc_rolls_in_pkg: 'Liczba rolek w op.',
    dc_rolls_used: (n) => `Rolki (${n} szt.)`,
    dc_per_month_lbl: 'zł / miesiąc',
    dc_per_month_ph: 'zł/mies.',
    dc_pkg_price_full2: 'Cena opakowania (zł)',
    dc_add_expense: '+ Dodaj ekstra wydatek',
    dc_add_item: '+ Dodaj produkt',
    dc_other_lbl: 'Inne',
    dc_fixed_lbl: 'Stałe',
    dc_pcs_per_month: 'Szt./mies.',
    dc_price_per_pkg2: 'Cena/opak. (zł)',
    dc_toothbrushing: 'Mycie zębów',
    dc_hairwashing: 'Mycie włosów',
    dc_bathing: 'Kąpiel / prysznic',
    dc_toilet_paper: 'Papier toaletowy',
    dc_brushing_times: 'Razy dziennie',
    dc_toothpaste_g: 'Pasty na raz (g)',
    dc_tube_ml: 'Pojemność tubki (ml)',
    dc_tube_price: 'Cena tubki (zł)',
    dc_toothbrush_price: 'Cena szczoteczki (zł) — co 3 mies.',
    dc_hair_times_week: 'Razy w tygodniu',
    dc_shampoo: 'Szampon',
    dc_conditioner: 'Odżywka',
    dc_pumps: 'Wyciśnięcia (1=5ml)',
    dc_gel: 'Żel',
    dc_soap: 'Mydło',
    dc_bar_size_g: 'Wielkość kostki (g)',
    dc_teeth_lbl: 'Zęby',
    dc_hair_lbl: 'Włosy',
    dc_bath_lbl: 'Kąpiel',
    dc_toilet_paper_short: 'Papier toa.',
    dc_deodorant_ph: 'np. Dezodorant',
    dc_trash: 'Śmieci',
    dc_cleaning_fluids: 'Płyny i akcesoria',
    dc_bags_per_week: 'Worków w tygodniu',
    dc_bags_in_pkg: 'Worków w opakowaniu',
    dc_cleaning_fluid_ph: 'np. Płyn uniwersalny',
    dc_rubbish_bags_lbl: 'Worki na śmieci',
    dc_hand_wash: 'Ręcznie',
    dc_dishwasher: 'Zmywarka',
    dc_how_long_lasts: 'Na ile wystarcza pojemnik?',
    dc_days_unit: 'Dni',
    dc_months_unit: 'Miesiące',
    dc_uses_per_week: 'Użyć na tydzień',
    dc_pods_in_pkg: 'Kapsułek w opakowaniu',
    dc_nursery: 'Przedszkole / Żłobek',
    dc_school_lunch: 'Obiad w szkole / Żłobku',
    dc_activities: 'Zajęcia dodatkowe',
    dc_tutoring: 'Korepetycje',
    dc_school_supplies: 'Materiały szkolne',
    dc_school_transport: 'Dojazdy do szkoły',
    dc_clothing: 'Odzież i obuwie',
    dc_pocket_money: 'Kieszonkowe',
    dc_toys: 'Zabawki',
    dc_cosmetics_lbl: 'Kosmetyki',
    dc_nappies: 'Pieluchy',
    dc_formula: 'Mleko modyfikowane',
    dc_nappies_per_day: 'Ile dziennie (szt.)',
    dc_nappies_in_pkg: 'Ilość w opakowaniu',
    dc_servings_per_day: 'Ile porcji dziennie',
    dc_servings_in_pkg: 'Porcji w opakowaniu',
    dc_nappies_lbl: 'Pieluchy',
    dc_formula_lbl: 'Mleko',
    dc_holiday_ph: 'np. Kolonia',
    dc_dry_food: 'Sucha karma',
    dc_wet_food: 'Mokra karma',
    dc_litter: 'Żwirek / ściółka',
    dc_vet: 'Weterynarz',
    dc_grooming: 'Pielęgnacja',
    dc_accessories: 'Akcesoria / zabawki',
    dc_dry_g_per_day: 'Dzienne spożycie (g)',
    dc_pkg_size_g: 'Wielkość opakowania (g)',
    dc_cans_per_day: 'Puszek / saszetek dziennie',
    dc_can_weight_g: 'Gramatura puszki / saszetki (g)',
    dc_can_price: 'Cena puszki / saszetki (zł)',
    dc_change_days: 'Wymiana co ile dni',
    dc_litter_per_change: 'Ilość na wymianę (l)',
    dc_pkg_size_l: 'Wielkość opakowania (l)',
    dc_vet_short: 'Wet. / piel. / akc.',
    dc_pet_toy_ph: 'np. Zabawki',
    dc_doctors: 'Wizyty lekarskie',
    dc_medicine: 'Leki',
    dc_paper_a4: 'Papier A4 (ryza 500 ark.)',
    dc_ink: 'Tusz / toner do drukarki',
    dc_notebook: 'Notatnik / Zeszyty',
    dc_pens: 'Długopisy',
    dc_supplies_lbl: 'Artykuły',
    dc_pencils_ph: 'np. Kredki',
    dc_fuel_price_lbl: 'Cena paliwa (zł/l)',
    dc_fetch_fuel: '↻ Pobierz cenę z internetu',
    dc_fetch_fuel_error: 'Nie udało się pobrać cen',
    dc_fuel_petrol: 'Benzyna',
    dc_media_phone: 'Telefon',
    dc_km_per_day: 'Km dziennie',
    dc_consumption_lbl: 'Spalanie (l/100km)',
    dc_consumption_sec: 'Zużycie',
    dc_packaging_sec: 'Opakowanie',
    dc_cups_per_day2: 'Kubków / dzień',
    dc_spoons_per_cup2: (g) => `Łyżek kawy / kubek (=${g}g)`,
    dc_sweetener_q: 'Słodzi?',
    dc_sugar: 'Cukier',
    dc_sweetener: 'Słodzik',
    dc_spoons_s: (g) => `Łyżek / kubek (=${g}g)`,
    dc_price_per_kg: 'Cena (zł/kg)',
    dc_milk_q: 'Mleko / Śmietanka?',
    dc_milk: 'Mleko',
    dc_cream: 'Śmietanka',
    dc_pkg_weight_g: 'Waga op. (g)',
    dc_cups_summary: (n) => `${n} kub./dzień`,
    dc_cups_total: (n) => `= ${n} kubków`,
    dc_sachets_in_pkg: 'Saszetek w op.',
    dc_pkg_capacity_l2: 'Pojemność op. (l)',
    dc_sweetness: 'Słodkość',
    dc_syrup_sec: 'Syrop',
    dc_syrup_ml: 'Pojemność syropu (ml)',
    dc_syrup_price: 'Cena syropu (zł)',
    dc_gas_cylinder: 'Butla gazowa',
    dc_exchange_days: 'Wymiana co (dni)',
    dc_exchange_cost: 'Koszt wymiany (zł)',
    dc_liters_summary: (n) => `${n} l/dzień`,
    dc_liters_total: (n) => `= ${n} l`,
    drink_coffee: 'Kawa',
    drink_tea: 'Herbata',
    drink_soft_drinks: 'Napoje',
    drink_water: 'Woda',
    drink_soda_stream: 'Soda Stream',
    // MacroCalculator
    macro_your_data: 'Twoje dane',
    macro_gender: 'Płeć',
    macro_male: 'Mężczyzna',
    macro_female: 'Kobieta',
    macro_age: 'Wiek (lata)',
    macro_weight: 'Masa ciała (kg)',
    macro_height: 'Wzrost (cm)',
    macro_activity: 'Poziom aktywności',
    macro_goal: 'Cel',
    macro_cut: 'Redukcja',
    macro_maintain: 'Utrzymanie',
    macro_bulk: 'Masa',
    macro_aggr_cut: 'Ostra redukcja',
    macro_aggr_not_rec: '(niezalecane)',
    macro_save_goal: 'Zapisz jako cel i pokaż w kalendarzu',
    macro_daily_goal: 'Cel dzienny makro',
    macro_kcal_day: 'kcal/dzień',
    macro_protein: 'Białko',
    macro_fat: 'Tłuszcze',
    macro_carbs: 'Węglowodany',
    macro_caloric_needs: 'ZAPOTRZEBOWANIE KALORYCZNE',
    macro_bmr_label: 'kcal / podstawowe',
    macro_tdee_label: 'kcal / z aktywnością',
    macro_bmr_warning: (bmr) => `Nie schodź poniżej BMR (${bmr} kcal)`,
    macro_active_goal: 'AKTYWNY CEL W KALENDARZU',
    macro_how_title: 'Jak liczymy makro?',
    macro_bmi_normal: 'Norma:',
    macro_act_sedentary: 'Siedzący (brak aktywności)',
    macro_act_light: 'Lekka (1–2x/tydzień)',
    macro_act_moderate: 'Umiarkowana (3–5x/tydzień)',
    macro_act_active: 'Aktywna (6–7x/tydzień)',
    macro_act_very_active: 'Bardzo aktywna (2x dziennie)',
    macro_underweight: 'Niedowaga',
    macro_normal: 'Norma',
    macro_overweight: 'Nadwaga',
    macro_obese: 'Otyłość',
    macro_goal_suffix: (n, label) => `${label} ${n > 0 ? '+' : ''}${n} kcal / dzień`,
    legend_obesity_title: 'Korekta dla nadwagi / otyłości:',
    legend_obesity_body1: 'białko liczone od masy skorygowanej',
    legend_obesity_body2: (w) => `(nie od rzeczywistej ${w} kg), żeby uniknąć zawyżonych wartości`,
    legend_obesity_formula: (ibw) => `Wzór: idealna waga (${ibw} kg) + 25% nadwyżki.`,
    legend_protein_by_goal: 'Ilość białka zależy od celu:',
    legend_protein_lose: '2,2 g × kg (redukcja - ochrona mięśni)',
    legend_protein_maintain: '1,8 g × kg (utrzymanie)',
    legend_protein_gain: '2,0 g × kg (masa - budowa mięśni)',
    legend_protein_extreme: '2,2 g × kg (ostra redukcja - ochrona mięśni)',
    legend_protein_basis: 'Podstawa obliczeń',
    legend_1g_protein: '1 g białka = 4 kcal.',
    legend_fat_fixed: 'Stały udział',
    legend_fat_of_kcal: 'kalorii docelowych',
    legend_fat_div9: 'podzielony przez 9 kcal/g',
    legend_fat_note: 'Tłuszcze są niezbędne dla hormonów i wchłaniania witamin - poniżej 20% nie jest zalecane.',
    legend_carbs_desc: 'Reszta kalorii po odjęciu białka i tłuszczów, podzielona przez 4 kcal/g.',
    legend_formula: 'Wzór',
    legend_carbs_formula: '(cel kcal − białko×4 − tłuszcz×9) ÷ 4',
    legend_bmr_desc: '(podstawowa przemiana materii) - Mifflin-St Jeor:',
    legend_bmr_formula: 'waga + 6,25×wzrost − 5×wiek + 5 (M) / −161 (K)',
    legend_tdee_desc: 'współczynnik aktywności',
    quote_1: '„Perfekcjonizm jest wrogiem postępu."',
    quote_1_author: '- Winston Churchill',
    quote_2: '„Jesteśmy tym, co regularnie robimy. Doskonałość nie jest więc czynem, lecz nawykiem."',
    quote_2_author: '- Arystoteles',
    // Recipes extra
    search_inspiration: 'SZUKASZ INSPIRACJI?',
    use_ai_hint: 'Możesz też wejść na',
    use_ai_hint2: ', użyć prompta poniżej i tam wkleić swój przepis, a następnie odpowiedź wkleić do okna po lewej i użyć',
    copy_prompt_btn: 'Kopiuj prompt',
    copied_label: '✓ Skopiowano!',
    opt1_short: 'Opcja 1:',
    opt2_short: 'Opcja 2:',
    fetch_macro_btn: 'Pobierz makra',
    price_per_opak_lbl: 'Cena/op.',
    product_added_ok: 'Produkt dodany',
    del_sel_products_title: 'Usuń zaznaczone produkty',
    no_limit_label: 'Bez limitu',
    daily_limit_remaining: (n) => `Limit: 2 dziennie.${n !== null ? ` Pozostało: ${n}` : ''}`,
    recipe_prompt: `Jesteś asystentem do wyodrębniania składników z przepisów. Gdy wkleję przepis, zwróć:\n\n{{name}} w pierwszej linii\nNastępnie TYLKO CSV składników w formacie: nazwa,ilosc,jednostka\n\nZasady:\n- Nagłówek CSV zawsze: nazwa,ilosc,jednostka\n- ilosc = liczba z kropką (np. 0.5, 200, 1)\n- jednostka = kg / g / l / ml / szt / łyżka / łyżeczka / szklanka\n- Przeliczaj opisy na liczby: "pół" → 0.5, "trzy" → 3, "szczypta" → 1 (jednostka: szczypta)\n- Żadnych komentarzy -- tylko {{name}} w pierwszej linii i sam CSV`,
    missing_product_hint: 'Wiersze z pomarańczowym tłem wymagają ręcznego dopasowania produktu z listy. Gdy składnika nie ma na liście, kliknij «Dodaj do listy Produkty». Produkty możesz później edytować w zakładce Produkty.',
    add_to_products_btn: 'Dodaj do listy Produkty',
    add_product_inline_btn: 'Dodaj produkt',
    add_ing_new_product: 'Dodaj nowy produkt',
    pkg_in_packaging: 'W opakowaniu',
    pkg_by_weight: 'Na wagę',
    pkg_qty_inline: 'Ilość w opakowaniu',
    pkg_qty_ph: 'np. 100',
    price_per_pkg_kg: 'Cena za opakowanie / kg (zł)',
    meal_type_label: 'Typ posiłku:',
    recipe_servings_label: 'Porcji z przepisu',
    recipe_servings_hint: 'Liczba porcji z oryginalnego przepisu — składniki zostaną podzielone przez tę wartość, aby w kalendarzu pokazać porcję na 1 osobę.',
    err_no_servings: 'Podaj liczbę porcji z przepisu (min. 1)',
    meal_type_required: 'wymagane',
    matched_product_col: 'Dopasowany produkt',
    recipe_not_found: (name) => `Nie znaleziono przepisu „${name}"`,
    del_selected_recipes: (n) => `Usuń wybrane (${n})`,
    del_all_recipes: 'Usuń wszystkie',
    select_label: 'Zaznacz',
    deselect_label: 'Odznacz',
    confirm_del_selected_recipes: (n) => `Czy na pewno chcesz usunąć ${n} zaznaczonych przepisów?`,
    confirm_del_all_recipes: (n) => `Czy na pewno chcesz usunąć wszystkie ${n} przepisów?`,
    del_selected_label: (n) => `Usuń zaznaczone (${n})`,
    del_all_recipes_title: 'Usuń wszystkie przepisy',
    del_selected_recipes_title: 'Usuń zaznaczone przepisy',
    recipe_deleted: 'Przepis usunięty',
    all_recipes_deleted: 'Wszystkie przepisy usunięte',
    recipes_deleted: (n) => `Usunięto ${n} przepisów`,
    recipe_saved: 'Przepis dodany',
    add_ing_label: '+ Dodaj składnik',
    loading_ing: 'Ładowanie składników…',
    del_ing_title: 'Usuń składnik',
    del_ing_confirm: (name) => `Usunąć „${name}" z przepisu?`,
    recipe_search_ph: 'Szukaj przepisu...',
    see_recipe: 'Zobacz przepis ↗',
    recipe_col_name: 'Nazwa',
    recipe_col_kcalmacro: 'Kcal / Makro',
    recipe_col_meal: 'Posiłek',
    recipe_col_price: 'Cena',
    plus_macro: '+ makro',
    price_input_ph: 'cena',
    pkg_input_ph: 'opak.',
    existing_product: 'istn. produkt',
    shown_of: (shown, total, type) => `Pokazano ${shown} z ${total} ${type}…`,
    fav_add: 'Dodaj do ulubionych',
    fav_remove: 'Usuń z ulubionych',
    click_to_edit: 'Kliknij dwukrotnie aby edytować',
    click_change_meal: 'Kliknij aby zmienić typ posiłku',
    no_type: '+ typ',
    no_type_label: '— brak —',
    delete_confirm_recipe: (name) => `Czy na pewno chcesz usunąć „${name}"?`,
    del_recipe_title: 'Usuń przepis',
    save_changes_label: 'Zmiany zapisane',
    name_saved_label: 'Nazwa zapisana',
    save_error_label: 'Błąd zapisu',
    recipe_name_max: 'Nazwa przepisu max 200 znaków',
    each_ing_has_product: 'Wybierz produkt dla każdego składnika',
    weight_range_error: 'Gramatura musi być między 1 a 99999',
    category_error: 'Błąd zapisu kategorii',
    select_meal_type: 'Wybierz typ posiłku (Śniadanie / Obiad / Kolacja / Snack / Deser)',
    // Products extra
    search_products_hint: 'SZUKASZ PRODUKTÓW?',
    product_paste_ph: 'Wklej produkt ze strony sklepu lub sam wpisz np:\n\nBanany Premium Owoce Auchan na wagę kiść 4-6 szt ok. 1 kg\nSprzedawcą jest Auchan Polska Sp. z o.o.\n1kg ~szacunkowa porcja 6,98 zł/kg\n\nBanan 1kg 7zł',
    opt1_s2_pre: 'Kliknij', opt1_s2_suf: 'wyciągnie produkty i ceny',
    opt1_s3_pre: 'Sprawdź dopasowania i kliknij',
    apply_ai_label: 'Zastosuj przez AI', apply_changes_label: 'Zastosuj zmiany',
    apply_file_label: 'Zastosuj plik',
    opt2_required_fmt: 'Wymagany format:', opt2_or: 'lub:',
    opt2_manually: 'ręcznie wprowadź gramaturę i jednostkę',
    opt2_upload_pre: 'Wgraj plik i kliknij',
    go_to_ai_pre: 'Przejdź na', go_to_ai_suf: 'i wklej następujący prompt:',
    check_data_label: 'Sprawdź czy dane są poprawne:',
    price_per_kg_lbl: 'Cena / kg (zł)',
    price_ph: 'np. 3,49',
    pkg_ph: 'np. 1000',
    save_doc_step_pre: 'Zapisz dokument z odpowiedzią jako',
    csv_format_full: 'nazwa,gramatura,jednostka,cena',
    csv_format_short: 'nazwa,cena',
    pkg_btn: 'W opak.',
    weight_btn: 'Na wagę',
    pkg_capacity_lbl: 'Pojemność opakowania',
    quick_update_hint: 'Chcesz szybko uzupełnić / zaktualizować listę produktów?',
    go_to_hint: 'Przejdź na',
    paste_products_step: 'Wklej listę produktów / podaj produkty',
    create_doc_step: 'Utwórz nowy dokument tekstowy',
    copy_response_step: 'Skopiuj odpowiedź z Claude / Gemini / ChatGPT do dokumentu',
    save_doc_step: (code) => `Zapisz dokument z odpowiedzią jako ${code}`,
    drag_doc_step: 'Zapisany dokument następnie przeciągnij w okno',
    products_prompt: `Jesteś asystentem do formatowania list produktów. Gdy wkleję Ci listę produktów w dowolnym formacie, zwróć TYLKO gotowy CSV w formacie:\nnazwa,gramatura,jednostka,cena\nZasady:\n- Pierwsza linia to zawsze nagłówek: nazwa,gramatura,jednostka,cena\n- gramatura = liczba (np. 1, 0.5, 200)\n- jednostka = kg / g / l / ml / szt\n- cena = liczba z kropką (np. 4.50)\n- Jeśli czegoś brakuje: gramatura = 1, jednostka = szt, cena = 0.00\n- Żadnego komentarza -- tylko sam CSV\n\nCzekam na moją listę.`,
    del_selected_products: (n) => `Usuń wybrane (${n})`,
    del_all_products: 'Usuń wszystkie',
    confirm_del_selected_products: (n) => `Czy na pewno chcesz usunąć ${n} zaznaczonych produktów?`,
    confirm_del_all_products: (n) => `Czy na pewno chcesz usunąć wszystkie ${n} produktów? Tej operacji nie można cofnąć.`,
    del_selected_products_title: 'Usuń zaznaczone produkty',
    del_all_products_title: 'Usuń wszystkie produkty',
    products_deleted: (n) => `Usunięto ${n} produktów`,
    all_products_deleted: 'Wszystkie produkty usunięte',
    product_added: 'Produkt dodany',
    product_deleted: 'Produkt usunięty',
    changes_saved: 'Zapisano zmiany',
    product_not_found: (name) => `Nie znaleziono produktu „${name}"`,
    pkg_capacity_col: 'Pojemność Opakowania',
    price_pkg_kg_col: 'Cena (opak/kg)',
    by_weight_label: 'Na wagę',
    price_kg_edit: 'Cena/kg',
    price_op_edit: 'Cena/op.',
    get_macros_btn: 'Pobierz makra',
    pkg_op_btn: 'W op.',
    shown_products: (shown, total) => `Pokazano ${shown} z ${total} produktów…`,
    product_exists_err: (name) => `Produkt „${name}" już istnieje na liście`,
    product_adding: (name) => `Produkt „${name}" dodany — pobieram makro...`,
    product_added_macro: (name, hasMacro) => `Produkt „${name}" dodany${hasMacro ? ' z makro' : ''}`,
    valid_price_err: 'Wprowadź prawidłową cenę dla zaznaczonych produktów',
    price_max_err: 'Cena nie może przekraczać 99999 zł',
    weight_max_err: 'Gramatura nie może przekraczać 99999',
    name_max_err: 'Nazwa produktu max 200 znaków',
    fill_name_err: 'Uzupełnij nazwę dla nowych produktów',
    save_products_err: 'Błąd przy zapisywaniu produktów',
    del_during_err: 'Błąd podczas usuwania',
    // Summary extra
    food_expenses_label: 'Wydatki na jedzenie',
    include_label: 'Uwzględnij:',
    no_data_label: 'Brak danych',
    total_label: 'Łącznie',
    create_template_btn: '+ Stwórz szablon',
    go_to_calendar_btn: 'Idź do kalendarza',
    delete_template_btn: 'Usuń',
    from_label: 'Od',
    to_label: 'Do',
    // Export extra
    week_preview: 'Podgląd tygodnia',
    loading_preview: 'Ładowanie...',
    no_meals_preview: 'Brak zaplanowanych posiłków',
    days_with_meals: (days, total) => `${days} ${days === 1 ? 'dzień' : 'dni'} z posiłkami · ${total} ${total === 1 ? 'posiłek' : total < 5 ? 'posiłki' : 'posiłków'}`,
    shop_list_title: 'Lista zakupów',
    selected_days: (n) => `Zaznaczono: ${n} ${n === 1 ? 'dzień' : 'dni'}`,
    include_profiles: 'Uwzględnij profile',
    export_recipe_search: 'Wyszukaj przepis...',
    export_no_results: 'Brak wyników',
    export_do_export: 'Eksportuj składniki',
    kogo_uwzgledniamy: 'Kogo uwzględniamy',
    select_at_least_one_day: 'Zaznacz co najmniej jeden dzień',
    export_macro_err: 'Uzupełnij dane w Kalkulatorze Makro i zapisz je przed eksportem.',
    export_macro_gen_err: 'Nie udało się wygenerować karty — sprawdź dane w kalkulatorze.',
    export_wydatki_err: 'Nie udało się pobrać danych wydatków',
    export_calendar_err: 'Nie udało się pobrać kalendarza',
    export_shop_list_err: 'Nie udało się wygenerować listy zakupów',
    export_select_period: 'Wybierz okres',
    export_select_recipe: 'Wybierz przepis',
    // MacroCalculator extra
    fill_left: 'Uzupełnij dane po lewej',
    macro_goals_saved: 'Cele makro zapisane! Kolory pojawią się w kalendarzu.',
    lost_receipt_hint: 'Zgubiłeś paragon? Otwórz paragon w aplikacji sklepu, zrób screenshot i wgraj',
    no_assignment_hint: 'Brak przypisania — przypisz do podobnego produktu lub zostaw',
    new_product_opt: '➕ Utwórz nowy produkt',
    create_new_option: (name) => `+ Utwórz nowy: „${name}"`,
    // MemberPicker (sidebar — wszystkie zakładki)
    member_added: (name) => `Dodano „${name}"`,
    err_member_add: 'Błąd dodawania',
    member_renamed: 'Nazwa zmieniona',
    err_member_rename: 'Błąd zmiany nazwy',
    member_delete_title: (name) => `Usuń „${name}"`,
    member_delete_confirm: 'Wszystkie zaplanowane posiłki tej osoby zostaną usunięte. Tej operacji nie można cofnąć.',
    member_deleted: (name) => `Usunięto „${name}"`,
    err_member_delete: 'Błąd usuwania',
    member_switch_hint: 'Kliknij aby przełączyć · Dwuklik aby zmienić nazwę',
    member_name_ph: 'Imię...',
    member_add_person: 'Dodaj osobę',
    // Products — potwierdzenia
    delete_confirm_product: (name) => `Czy na pewno chcesz usunąć „${name}"? Tej operacji nie można cofnąć.`,
    // Calendar
    recipes_count: (n) => {
      if (n === 1) return '1 przepis';
      if (n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 10 || n % 100 > 20)) return `${n} przepisy`;
      return `${n} przepisów`;
    },
    click_edit_macro: 'Kliknij aby edytować makro (wartości na 100g)',
    macro_day_label: 'Makro',
    cal_no_recipes_match: (q) => `Brak przepisów pasujących do „${q}"`,
    shown_recipes: (shown, total) => `Pokazano ${shown} z ${total} przepisów…`,
    // MacroCalculator — placeholdery
    placeholder_eg_age: 'np. 28',
    placeholder_eg_weight: 'np. 75',
    placeholder_eg_height: 'np. 178',
    // Login
    login_privacy_prefix: 'Zakładając konto akceptujesz ',
    login_privacy_link: 'Politykę Prywatności',
    login_privacy_suffix: ' Ontrack.',
    // Profil — zmiana języka konta
    profile_lang_name_pl: '🇵🇱 Polski',
    profile_lang_name_en: '🇬🇧 English',
    profile_lang_desc: (name) => `Obecny język konta: ${name}. Określa język domyślnych produktów i przepisów.`,
    profile_lang_change_title: 'Zmienić język konta?',
    profile_lang_warning_label: 'Uwaga:',
    profile_lang_warning_body: (from, to) => `Dane które masz w wersji ${from} (produkty, przepisy, plan posiłków) nie będą dostępne po przełączeniu na ${to}.`,
    profile_lang_warning_note: 'Twoje istniejące dane nie zostaną usunięte — ale zostały stworzone w innej wersji językowej i nie będą pasować do nowych domyślnych.',
    profile_lang_change_confirm: 'Zmień mimo to',
    // Wydatki — okres napojów
    drinks_period_week: 'tydzień (7 dni)',
    drinks_period_month: (d) => `miesiąc (${d} dni)`,
    drinks_period_custom: (d) => `wybrany okres (${d} dni)`,
    // Eksport — pomoc i placeholdery
    date_format_ph: 'dd.mm.rrrr',
    export_help_summary: 'Wydatki na jedzenie + koszty stałe zaznaczone w zakładce Wydatki (czynsz, prąd, gaz…), przeliczone proporcjonalnie na liczbę dni.',
    export_help_macro: 'Eksport danych z Kalkulatora Makro — dane osobowe, BMI, zapotrzebowanie kaloryczne i docelowe makroskładniki.',
    export_help_calendar: 'Wydruk planu posiłków. Przed wydrukiem możesz włączyć lub wyłączyć widoczność kcal i makro przy każdym dniu.',
    export_help_ingredients: 'Wyszukaj przepis wpisując jego nazwę, a następnie wyeksportuj listę składników z ilościami i cenami gotową do wydruku.',
    export_help_shopping: 'Zaznacz dni, lista produktów z przepisów przeliczona na opakowania. Przed wydrukiem możesz usunąć pozycje z listy zakupów.',
    export_help_preview: 'Miniaturowy widok kalendarza reagujący na wybrany okres (bieżący tydzień / miesiąc / zakres własny). Pokazuje jakie posiłki są zaplanowane w danym dniu.',
    eg_prefix: 'np.',
  },
  en: {
    // App/Nav
    loading: 'Loading…',
    tab_macro: 'Macro Calculator',
    tab_calendar: 'Meal Planner',
    tab_recipes: 'Recipes',
    tab_products: 'Products',
    tab_summary: 'Expenses',
    tab_export: 'Export',
    logout: 'Log out',
    profile: 'Profile',
    account: 'Account',
    // Profile modal
    my_profile: 'My Profile',
    delete_account: 'Delete account',
    delete_confirm: 'Are you sure you want to delete your account? All data will be permanently deleted. This action cannot be undone.',
    close: 'Close',
    deleting: 'Deleting…',
    show_tutorial: 'Show tutorial',
    // Login
    subtitle_login: 'Sign in to your account',
    subtitle_register: 'Create your Ontrack account',
    login_tagline: 'Plan meals. Track budget.',
    login_tagline_desc: 'Weekly calendar, recipes with cost and macros, and products with live prices from grocery stores.',
    login_feature_calendar: 'Weekly meal calendar for the whole household',
    login_feature_recipes: 'Recipes with per-serving cost and macros',
    login_feature_budget: 'Products priced from Aldi, Auchan and Biedronka',
    login_value_prop: '450+ products and 65+ recipes ready after sign-up',
    login_tab_login: 'Sign in',
    login_tab_register: 'Sign up',
    login_username_lbl: 'USERNAME',
    login_password_lbl: 'PASSWORD',
    login_busy_login: 'Signing in…',
    login_busy_register: 'Creating account…',
    google_btn: 'Continue with Google',
    login_username_ph: 'e.g. johndoe',
    login_email_ph: 'Email address',
    login_password_ph: 'Min. 8 characters',
    login_submit: 'Sign in',
    login_register_submit: 'Create account',
    login_or: 'or',
    login_switch_register: "Don't have an account? Sign up",
    login_switch_login: 'Already have an account? Sign in',
    err_login_failed: 'Invalid username or password',
    err_register_failed: 'Registration failed — please try again',
    account_language: 'ACCOUNT LANGUAGE',
    // Calendar arrays
    slot_labels: ['Breakfast', 'Second breakfast', 'Lunch', 'Afternoon snack', 'Dinner'],
    month_names: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    day_short: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    day_full: ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
    // Calendar UI
    how_to_title: 'How to use the calendar?',
    expand: 'Expand',
    collapse: 'Collapse',
    tpl_title: 'Create template',
    your_tpls: 'Saved templates',
    tpl_drag_hint: 'Drag recipes from Recipes to days of the week, then name and save your template. Clear resets the template.',
    tpl_name_ph: 'Template name (e.g. Fit Week)',
    save_tpl: 'Save template',
    clear: 'Clear',
    no_tpls: 'No saved templates — create the first one above.',
    apply_from_mon: 'Apply from Monday:',
    apply: 'Apply',
    meals_count: (n) => `${n} meals`,
    carousel_title: 'Recipes',
    search_recipe_ph: 'Search recipe...',
    cat_all: 'All',
    cat_breakfast: 'Breakfast',
    cat_lunch: 'Lunch',
    cat_dinner: 'Dinner',
    cat_snack: 'Snack',
    cat_dessert: 'Dessert',
    drag_to_cal: 'Drag to a day in the calendar or to a template below',
    no_recipes_cal: 'No recipes',
    err_load_recipes: 'Error loading recipes',
    err_load_plan: 'Error loading plan',
    err_del_meal: 'Error deleting meal',
    err_del_meals: 'Error deleting meals',
    err_del_week: 'Error deleting week',
    err_paste_day: 'Error pasting day',
    err_paste_week: 'Error pasting week',
    err_copy_day: 'Error copying day',
    err_add_meal: 'Error adding meal',
    err_move_meal: 'Error moving meal',
    confirm_del_day: (n, d) => `Delete all ${n} meals from ${d}?`,
    confirm_del_week: (n) => `Delete all ${n} meals from this week?`,
    toast_copy_day: (d) => `⧉ Day ${d} copied`,
    toast_copy_week: '⧉ Week copied to clipboard and template editor',
    clipboard_day: (d) => `Clipboard: day ${d}`,
    clipboard_week: (d) => `Clipboard: week from ${d}`,
    clear_clipboard: '✕ clear',
    paste_day_hint: 'click ⎘ on another day to paste',
    paste_week_hint: 'click ⎘ next to another week to paste',
    drag_day_title: 'Drag day',
    copy_day_title: 'Copy day',
    paste_day_title: 'Paste day',
    del_day_title: 'Delete all meals for this day',
    copy_week_title: 'Copy week / load into template',
    paste_week_title: 'Paste week',
    del_week_title: 'Delete entire week',
    btn_grab: 'Grab',
    btn_copy: 'Copy',
    btn_paste: 'Paste',
    btn_delete: 'Delete',
    btn_copied: 'Copied',
    day_deleted_ok: 'Day deleted',
    week_deleted_ok: 'Week deleted',
    btn_create_recipe: '+ Create recipe',
    btn_create_template: '+ Create template',
    btn_go_calendar: 'Go to calendar',
    current_profile: 'Current profile',
    est_cost: 'est. cost',
    recipe_cost_lbl: 'Est. recipe cost',
    currency: '£',
    macro_p: 'P',
    macro_f: 'F',
    macro_c: 'C',
    unit_pcs: 'pcs',
    ht_meals_title: ' Meal planning',
    ht_meals_1: 'Grab a recipe from the carousel and drag it to a slot in a day (5 slots: breakfast–dinner)',
    ht_meals_2: 'You can move a meal between days by dragging it by name',
    ht_meals_3: 'Click ✕ next to a meal to remove it, or 🗑 in the day header to clear the whole day',
    ht_copy_title: ' Copying days and weeks',
    ht_copy_1: '⧉ in the day header — copies the day to clipboard',
    ht_copy_2: '⎘ — pastes the clipboard to another day',
    ht_copy_3: '⠿ next to the day number — grab and drag a day to another day',
    ht_copy_4: '⧉ / ⎘ / 🗑 on the left of each row — copy, paste or delete an entire week',
    ht_tpl_title: ' Week templates',
    ht_tpl_1: 'Click ⧉ next to a week — loads meals into the template editor below',
    ht_tpl_2: 'In the editor, drag recipes from the carousel to days of the week',
    ht_tpl_3: 'Enter a name and click Save template',
    ht_tpl_4: 'You can apply the template to any future week',
    ht_macro_title: ' Macro colours in calendar',
    ht_macro_1: 'Save your macro goals in the "Macro Calculator" tab (kcal, protein, fat, carbs)',
    ht_macro_2: 'Each day with meals shows a summary: actual / goal',
    ht_macro_3: 'Green — within 10% of goal · Yellow — 10–25% · Red — more than 25% off',
    // Recipes
    add_recipe_title: 'Add recipe',
    how_to_recipe: 'How to add a recipe?',
    format_title: 'Text format:',
    fmt_1: 'First line - recipe name',
    fmt_1_rest: '— on the first line (required!)',
    fmt_2: 'Each ingredient on a separate line',
    fmt_3: 'Provide the ingredient name and amount with unit (g, ml, kg, l, tablespoon, teaspoon, cup…)',
    fmt_4: 'You can paste text from a recipe website',
    ai_tip: 'AI Parse - Gemini understands any format, grammar, and context.',
    regex_tip: 'Regex parse - fast, local, no limit. Requires amounts in the text.',
    daily_limit: 'Limit: 2 per day.',
    example: 'Example:',
    remaining_ai: (n) => `AI parses remaining today: ${n}`,
    recipe_ph: 'Paste or type a recipe...\n\n══ RECIPE NAME ══  ← first line!\nIngredient 1 - amount\nIngredient 2 - amount',
    parse_ai_btn: 'Parse with AI',
    parsing_ai: 'Gemini is analysing...',
    parse_regex_btn: 'Parse without AI',
    recipe_name_lbl: 'Recipe name',
    ingredients_lbl: (m, total) => `Ingredients — ${m}/${total} matched`,
    save_recipe: 'Save recipe',
    back: 'Back',
    original_text_lbl: 'Original recipe text — compare and manually add missing ingredients',
    recipe_list_title: 'Recipe list',
    no_recipes_add: 'No recipes — add the first one!',
    col_product: 'Product',
    col_weight: 'Weight',
    col_cost: 'Cost',
    info_section: 'Info',
    edit_notes: 'Edit',
    save_notes: 'Save',
    cancel: 'Cancel',
    no_notes: 'No notes — click Edit to add.',
    no_match_opt: '— no match —',
    err_save_recipe: 'Error saving recipe',
    err_save_notes: 'Error saving note',
    err_no_name: 'Recipe name is required',
    err_no_ingredients: 'No ingredient has a matched product',
    err_parse_regex: 'Could not extract ingredients — check the format',
    err_gemini_not_configured: 'AI parsing unavailable — use «Parse without AI»',
    err_gemini_busy: 'Gemini is busy — try again shortly or use «Parse without AI»',
    ai_parse_unavailable: 'AI not configured on server — use «Parse without AI»',
    confirm_del_recipe: 'Delete recipe?',
    show_ingredients: 'Ingredients',
    hide_ingredients: 'Collapse',
    delete: 'Delete',
    err_load_recipes_list: 'Error loading recipes',
    // Products
    add_product_title: 'Add product',
    basic_info: 'Basic information',
    product_name_lbl: 'Product name',
    product_name_ph: 'e.g. Natural yogurt',
    pkg_qty_lbl: 'Package quantity',
    unit_lbl: 'Unit',
    price_section: 'Price',
    pkg_price_lbl: 'Package price (£)',
    pkg_price_ph: 'e.g. 3.49',
    macro_auto_title: ' Macros & Calories — automatically',
    macro_auto_desc: 'After adding the product the system will automatically fetch Kcal, Protein, Fat and Carbohydrate values from Open Food Facts.',
    macro_edit_hint: 'Want to change them? Click Edit next to the product in the list below.',
    add_product_btn: 'Add product',
    import_title: 'Import prices from a receipt or CSV / TXT file',
    import_how_to: 'How to use import?',
    opt1_title: 'Option 1: Receipt photo',
    opt1_s1: 'Upload a JPG, PNG or WEBP photo',
    opt1_s2: 'Click Apply AI - Gemini will extract products and prices',
    opt1_s3: 'Check the matches and click Apply',
    ai_daily_lim: 'Limit: 2 AI imports per day.',
    ai_rem: (n) => ` Remaining: ${n}.`,
    opt2_title: 'Option 2: CSV / TXT file',
    opt2_fmt: 'Format:',
    opt2_s2: 'Upload the file and click Apply file',
    no_lim: '✓ No limit, no AI.',
    click_drag_file: 'Click or drag a file',
    file_types_hint: 'Option 1: JPG, PNG, WEBP — receipt (AI) | Option 2: TXT, CSV — price list (free)',
    click_change: 'Click to choose a different file',
    apply_ai_btn: ' Apply with AI (Gemini)',
    analyzing: ' Gemini is analysing...',
    apply_file_btn: ' Apply file (free)',
    processing: ' Processing...',
    check_prices: 'Select products, check prices and click Apply.',
    col_from_receipt: 'From receipt',
    col_qty: 'Qty',
    col_pkg_price: 'Pkg price',
    col_matched: 'Matched product',
    col_new_price: 'New price',
    no_match_prod: 'No match',
    apply_changes: 'Apply changes',
    import_review_hint_pre: 'Check the matches and fill in the data. Select',
    import_review_hint_suf: 'for vegetables, fruit and meat, then enter the price per kg.',
    create_new_product_opt: '➕ Create new product',
    create_new_product_label: 'Create new product',
    import_new_product_hint_suf: ' and it will be added to the Products list.',
    price_per_pkg_suffix: '/ pkg',
    import_updated_n: (n) => `Updated ${n}`,
    import_added_n: (n) => `Added ${n}`,
    import_done_suffix: 'products · Macros updated',
    product_list_title: 'Product list',
    col_name: 'Name',
    col_kcal: 'Kcal/100g',
    col_macro: 'Macro / 100g',
    col_price: 'Price',
    edit_btn: 'Edit',
    save_btn: 'Save',
    del_btn: 'Delete',
    confirm_del_product: 'Delete product?',
    no_products: 'No products',
    fetching_macro: '⏳ Fetching Macros and Calories from Open Food Facts…',
    kcal_lbl: 'Calories (kcal/100g)',
    protein_lbl: 'Protein (g/100g)',
    fat_lbl: 'Fat (g/100g)',
    carbs_lbl: 'Carbohydrates (g/100g)',
    auto_fill: ' Auto Fill',
    price_tip: (unit) => {
      const u = unit === 'szt' ? 'pc' : unit === 'ml' ? '100ml' : '100g';
      return ` Price: enter the package quantity and total price — the system will calculate zł/${u}.`;
    },
    auto_fill_tip: ' Auto Fill — fetches Kcal and Macros from Open Food Facts based on the product name.',
    err_fill_fields: 'Fill in all fields',
    err_not_found_off: (name) => `No data found for "${name}" — fill in manually`,
    err_off: 'Error connecting to Open Food Facts',
    err_load_products: 'Error loading products',
    macro_updated_suffix: ' · Macros updated automatically.',
    at_least_one: 'Select at least one product',
    // Summary
    summary_title: ' Shopping summary',
    date_from: 'From',
    date_to: 'To',
    generate: 'Generate',
    generating: 'Loading...',
    shopping_list_title: 'Shopping list',
    col_total_weight: 'Total weight',
    col_exact_pkgs: 'Packages (exact)',
    col_buy_pkgs: 'Packages (to buy)',
    col_price_per_pkg: 'Price/pkg',
    col_total_cost: 'Total cost',
    summary_period: (s, e) => `Period: ${s} — ${e}`,
    summary_prod_count: (n) => `Products: ${n}`,
    total_cost_lbl: 'Total shopping cost',
    no_meals_range: 'No meals planned in the selected period',
    err_load_summary: 'Error loading summary',
    err_select_range: 'Select a date range',
    err_date_order: 'Start date cannot be later than end date',
    // Summary new
    this_week: 'This week',
    this_month: 'This month',
    custom_period: 'Custom period',
    week_templates_sum: 'Weekly templates',
    show_product_list: 'Show product list',
    hide_product_list: 'Hide product list',
    go_edit_hint: 'go to Recipes to edit',
    est_weekly_cost: 'Estimated weekly cost',
    no_tpl_summary: 'No templates. Create them in the Meal Planner.',
    no_meals_period: 'No meals planned in this period',
    total_cost_lbl2: 'Total cost',
    meals_n: (n) => `${n} meals`,
    monthly_label: 'Monthly (£)',
    check_data_label: 'Check if the data is correct:',
    pkg_btn: 'In pkg.',
    pkg_capacity_lbl: 'Package size',
    weight_btn_short: 'By weight',
    // Export
    export_generate_title: 'Generate documents',
    export_period_label: 'PERIOD (EXPENSES & CALENDAR)',
    export_who_label: 'WHO TO INCLUDE',
    export_btn_summary: 'Expense summary',
    export_btn_macro: 'Macro card',
    export_btn_calendar: 'Calendar card',
    export_btn_ingredients: 'Recipe ingredients',
    export_shopping_hint: 'Select days — product list from recipes calculated in packages.',
    export_generate_list: 'Generate shopping list',
    export_include_profiles: 'INCLUDE PROFILES',
    export_how_title: 'How does export work?',
    export_preview_title: 'Preview',
    export_no_meals: 'No meals planned',
    food_label: 'Food',
    drinks_label: 'Drinks',
    by_weight_label: 'by weight',
    sold_by_weight_label: 'Sold by weight',
    col_weight_used: 'Weight used',
    col_pkg_size: 'Pkg size',
    col_pcs: 'Pcs.',
    col_price_per_pkg: 'Price/pkg.',
    col_in_stock: 'In stock',
    col_reduces_cost: 'reduces shopping cost',
    col_shopping: 'shopping',
    col_cost: 'cost',
    click_to_edit_hint: 'click to edit',
    stock_full: 'Full',
    stock_part: 'Part',
    enter_amount_label: 'Enter amount',
    search_product_ph: 'Search product...',
    quantity_ph: 'qty',
    add_btn: 'Add',
    col_pkg_capacity: 'PACKAGE SIZE',
    col_price_opak_kg: 'PRICE (PKG/KG)',
    expenses_select_title: 'SELECT EXPENSES TO INCLUDE',
    expenses_shared: 'shared',
    expenses_total: 'Total',
    exp_rent: 'Rent',
    exp_electricity: 'Electricity',
    exp_gas: 'Gas',
    exp_utilities: 'Utilities',
    exp_heating: 'Heating',
    exp_loan: 'Loan',
    exp_child: 'Child',
    exp_pet: 'Pet',
    exp_medical: 'Medical',
    exp_fuel: 'Fuel',
    exp_laundry: 'Laundry',
    exp_dishwashing: 'Dishwashing',
    exp_cleaning: 'Cleaning',
    exp_hygiene: 'Hygiene',
    exp_office_supplies: 'Office supplies',
    dc_washes_per_week: 'Washes / week',
    dc_detergent: 'DETERGENT',
    dc_powder: 'Powder', dc_liquid: 'Liquid', dc_capsules: 'Capsules',
    dc_grams_per_wash: 'Grams per wash',
    dc_pkg_capacity_kg: 'Package capacity (kg)',
    dc_pkg_capacity_l: 'Package capacity (l)',
    dc_pkg_capacity_ml: 'Package capacity (ml)',
    dc_pkg_price: 'Package price (£)',
    dc_pkg_price_full: 'Package price (£)',
    dc_fabric_softener: 'Fabric softener',
    dc_fabric_softener_section: 'FABRIC SOFTENER',
    dc_washes_per_pkg: 'Capsules per package',
    dc_cups_per_day: 'Cups per day',
    dc_sugar_type: 'Sweetener type',
    dc_spoons_per_cup: 'Teaspoons per cup',
    dc_milk_type: 'Milk / cream',
    dc_ml_per_cup: 'ml per cup',
    dc_per_day: 'per day',
    dc_per_week: '/ week',
    dc_days_label: (n) => `× ${n} days`,
    dc_monthly: 'Monthly (£)',
    dc_liters_per_day: 'Litres per day',
    dc_pkg_liters: 'Package capacity (l)',
    dc_soap_ml: 'Doses per wash',
    dc_rinse_ml: 'ml softener / wash',
    dc_capsules_per_pkg: 'Capsules per package',
    // DrinksCard — extra
    dc_rolls_per_day: 'Daily usage (rolls)',
    dc_rolls_in_pkg: 'Rolls per pack',
    dc_rolls_used: (n) => `Rolls (${n})`,
    dc_per_month_lbl: '/ month',
    dc_per_month_ph: '/month',
    dc_pkg_price_full2: 'Package price',
    dc_add_expense: '+ Add extra expense',
    dc_add_item: '+ Add item',
    dc_other_lbl: 'Other',
    dc_fixed_lbl: 'Fixed',
    dc_pcs_per_month: 'pcs/month',
    dc_price_per_pkg2: 'Price/pkg',
    dc_toothbrushing: 'Brushing teeth',
    dc_hairwashing: 'Washing hair',
    dc_bathing: 'Bathing / shower',
    dc_toilet_paper: 'Toilet paper',
    dc_brushing_times: 'Times per day',
    dc_toothpaste_g: 'Toothpaste per use (g)',
    dc_tube_ml: 'Tube size (ml)',
    dc_tube_price: 'Tube price',
    dc_toothbrush_price: 'Toothbrush price — every 3 months',
    dc_hair_times_week: 'Times per week',
    dc_shampoo: 'Shampoo',
    dc_conditioner: 'Conditioner',
    dc_pumps: 'Pumps (1=5ml)',
    dc_gel: 'Shower gel',
    dc_soap: 'Bar soap',
    dc_bar_size_g: 'Bar size (g)',
    dc_teeth_lbl: 'Teeth',
    dc_hair_lbl: 'Hair',
    dc_bath_lbl: 'Bath',
    dc_toilet_paper_short: 'Toilet paper',
    dc_deodorant_ph: 'e.g. Deodorant',
    dc_trash: 'Rubbish',
    dc_cleaning_fluids: 'Cleaning products',
    dc_bags_per_week: 'Bags per week',
    dc_bags_in_pkg: 'Bags per pack',
    dc_cleaning_fluid_ph: 'e.g. All-purpose cleaner',
    dc_rubbish_bags_lbl: 'Rubbish bags',
    dc_hand_wash: 'By hand',
    dc_dishwasher: 'Dishwasher',
    dc_how_long_lasts: 'How long does a bottle last?',
    dc_days_unit: 'Days',
    dc_months_unit: 'Months',
    dc_uses_per_week: 'Uses per week',
    dc_pods_in_pkg: 'Pods per pack',
    dc_nursery: 'Nursery / Crèche',
    dc_school_lunch: 'School / nursery lunch',
    dc_activities: 'Extracurricular activities',
    dc_tutoring: 'Tutoring',
    dc_school_supplies: 'School supplies',
    dc_school_transport: 'School transport',
    dc_clothing: 'Clothing & shoes',
    dc_pocket_money: 'Pocket money',
    dc_toys: 'Toys',
    dc_cosmetics_lbl: 'Toiletries',
    dc_nappies: 'Nappies',
    dc_formula: 'Formula milk',
    dc_nappies_per_day: 'Per day (pcs)',
    dc_nappies_in_pkg: 'Per pack',
    dc_servings_per_day: 'Servings per day',
    dc_servings_in_pkg: 'Servings per pack',
    dc_nappies_lbl: 'Nappies',
    dc_formula_lbl: 'Formula',
    dc_holiday_ph: 'e.g. Holiday camp',
    dc_dry_food: 'Dry food',
    dc_wet_food: 'Wet food',
    dc_litter: 'Cat litter',
    dc_vet: 'Vet',
    dc_grooming: 'Grooming',
    dc_accessories: 'Accessories / toys',
    dc_dry_g_per_day: 'Daily intake (g)',
    dc_pkg_size_g: 'Pack size (g)',
    dc_cans_per_day: 'Tins / pouches per day',
    dc_can_weight_g: 'Tin / pouch weight (g)',
    dc_can_price: 'Tin / pouch price',
    dc_change_days: 'Change every (days)',
    dc_litter_per_change: 'Amount per change (l)',
    dc_pkg_size_l: 'Pack size (l)',
    dc_vet_short: 'Vet / groom / acc.',
    dc_pet_toy_ph: 'e.g. Toys',
    dc_doctors: 'Doctor visits',
    dc_medicine: 'Medicine',
    dc_paper_a4: 'A4 paper (ream of 500)',
    dc_ink: 'Printer ink / toner',
    dc_notebook: 'Notebooks',
    dc_pens: 'Pens',
    dc_supplies_lbl: 'Supplies',
    dc_pencils_ph: 'e.g. Pencils',
    dc_fuel_price_lbl: 'Fuel price (per litre)',
    dc_fetch_fuel: '↻ Fetch prices',
    dc_fetch_fuel_error: 'Failed to fetch prices',
    dc_fuel_petrol: 'Petrol',
    dc_media_phone: 'Phone',
    dc_km_per_day: 'km per day',
    dc_consumption_lbl: 'Consumption (l/100km)',
    dc_consumption_sec: 'Consumption',
    dc_packaging_sec: 'Packaging',
    dc_cups_per_day2: 'Cups per day',
    dc_spoons_per_cup2: (g) => `Spoons per cup (=${g}g)`,
    dc_sweetener_q: 'Sweetener?',
    dc_sugar: 'Sugar',
    dc_sweetener: 'Sweetener',
    dc_spoons_s: (g) => `Spoons per cup (=${g}g)`,
    dc_price_per_kg: 'Price (per kg)',
    dc_milk_q: 'Milk / Cream?',
    dc_milk: 'Milk',
    dc_cream: 'Cream',
    dc_pkg_weight_g: 'Pack weight (g)',
    dc_cups_summary: (n) => `${n} cups/day`,
    dc_cups_total: (n) => `= ${n} cups`,
    dc_sachets_in_pkg: 'Sachets per pack',
    dc_pkg_capacity_l2: 'Pack size (l)',
    dc_sweetness: 'Sweetness',
    dc_syrup_sec: 'Syrup',
    dc_syrup_ml: 'Syrup bottle (ml)',
    dc_syrup_price: 'Syrup price',
    dc_gas_cylinder: 'Gas cylinder',
    dc_exchange_days: 'Exchange every (days)',
    dc_exchange_cost: 'Exchange cost',
    dc_liters_summary: (n) => `${n} l/day`,
    dc_liters_total: (n) => `= ${n} l`,
    drink_coffee: 'Coffee',
    drink_tea: 'Tea',
    drink_soft_drinks: 'Soft Drinks',
    drink_water: 'Water',
    drink_soda_stream: 'Soda Stream',
    // MacroCalculator
    macro_your_data: 'Your data',
    macro_gender: 'Gender',
    macro_male: 'Male',
    macro_female: 'Female',
    macro_age: 'Age (years)',
    macro_weight: 'Weight (kg)',
    macro_height: 'Height (cm)',
    macro_activity: 'Activity level',
    macro_goal: 'Goal',
    macro_cut: 'Cut',
    macro_maintain: 'Maintain',
    macro_bulk: 'Bulk',
    macro_aggr_cut: 'Aggressive cut',
    macro_aggr_not_rec: '(not recommended)',
    macro_save_goal: 'Save as goal and show in calendar',
    macro_daily_goal: 'Daily macro goal',
    macro_kcal_day: 'kcal/day',
    macro_protein: 'Protein',
    macro_fat: 'Fat',
    macro_carbs: 'Carbs',
    macro_caloric_needs: 'CALORIC NEEDS',
    macro_bmr_label: 'kcal / basic',
    macro_tdee_label: 'kcal / with activity',
    macro_bmr_warning: (bmr) => `Don't go below BMR (${bmr} kcal)`,
    macro_active_goal: 'ACTIVE GOAL IN CALENDAR',
    macro_how_title: 'Macro calculation formula',
    macro_bmi_normal: 'Normal:',
    macro_act_sedentary: 'Sedentary (no activity)',
    macro_act_light: 'Light (1–2x/week)',
    macro_act_moderate: 'Moderate (3–5x/week)',
    macro_act_active: 'Active (6–7x/week)',
    macro_act_very_active: 'Very active (2x daily)',
    macro_underweight: 'Underweight',
    macro_normal: 'Normal',
    macro_overweight: 'Overweight',
    macro_obese: 'Obese',
    macro_goal_suffix: (n, label) => `${label} ${n > 0 ? '+' : ''}${n} kcal / day`,
    legend_obesity_title: 'Overweight / obesity adjustment:',
    legend_obesity_body1: 'protein calculated from adjusted body weight',
    legend_obesity_body2: (w) => `(not from actual ${w} kg) to avoid inflated values`,
    legend_obesity_formula: (ibw) => `Formula: ideal weight (${ibw} kg) + 25% of excess.`,
    legend_protein_by_goal: 'Protein amount depends on goal:',
    legend_protein_lose: '2.2 g × kg (cut — muscle preservation)',
    legend_protein_maintain: '1.8 g × kg (maintenance)',
    legend_protein_gain: '2.0 g × kg (bulk — muscle building)',
    legend_protein_extreme: '2.2 g × kg (aggressive cut — muscle preservation)',
    legend_protein_basis: 'Calculation basis',
    legend_1g_protein: '1 g protein = 4 kcal.',
    legend_fat_fixed: 'Fixed share of',
    legend_fat_of_kcal: 'target calories',
    legend_fat_div9: 'divided by 9 kcal/g',
    legend_fat_note: 'Fat is essential for hormones and vitamin absorption — below 20% is not recommended.',
    legend_carbs_desc: 'Remaining calories after subtracting protein and fat, divided by 4 kcal/g.',
    legend_formula: 'Formula',
    legend_carbs_formula: '(target kcal − protein×4 − fat×9) ÷ 4',
    legend_bmr_desc: '(basal metabolic rate) — Mifflin-St Jeor:',
    legend_bmr_formula: 'weight + 6.25×height − 5×age + 5 (M) / −161 (F)',
    legend_tdee_desc: 'activity multiplier',
    quote_1: '"Perfectionism is the enemy of progress."',
    quote_1_author: '— Winston Churchill',
    quote_2: '"We are what we repeatedly do. Excellence, then, is not an act, but a habit."',
    quote_2_author: '— Aristotle',
    // Recipes extra
    search_inspiration: 'LOOKING FOR INSPIRATION?',
    use_ai_hint: 'You can also go to',
    use_ai_hint2: ', use the prompt below and paste your recipe there, then paste the response into the left panel and use',
    copy_prompt_btn: 'Copy prompt',
    copied_label: '✓ Copied!',
    opt1_short: 'Option 1:',
    opt2_short: 'Option 2:',
    fetch_macro_btn: 'Fetch macros',
    price_per_opak_lbl: 'Price/pkg.',
    product_added_ok: 'Product added',
    del_sel_products_title: 'Delete selected products',
    no_limit_label: 'No limit',
    daily_limit_remaining: (n) => `Limit: 2 per day.${n !== null ? ` Remaining: ${n}` : ''}`,
    recipe_prompt: `You are an assistant for extracting ingredients from recipes. When I paste a recipe, return:\n\n{{name}} on the first line\nThen ONLY a CSV of ingredients in the format: name,quantity,unit\n\nRules:\n- CSV header always: name,quantity,unit\n- quantity = number with a dot (e.g. 0.5, 200, 1)\n- unit = kg / g / l / ml / pcs / tablespoon / teaspoon / cup\n- Convert descriptions to numbers: "half" → 0.5, "three" → 3, "pinch" → 1 (unit: pinch)\n- No comments -- only {{name}} on the first line and the CSV itself`,
    missing_product_hint: 'Rows with an orange background need manual matching from the list. If an ingredient isn\'t on the list, click «Add to Products list». You can edit products later in the Products tab.',
    add_to_products_btn: 'Add to Products list',
    add_product_inline_btn: 'Add product',
    add_ing_new_product: 'Add new product',
    pkg_in_packaging: 'In package',
    pkg_by_weight: 'By weight',
    pkg_qty_inline: 'Package quantity',
    pkg_qty_ph: 'e.g. 100',
    price_per_pkg_kg: 'Price per package / kg',
    meal_type_label: 'Meal type:',
    recipe_servings_label: 'Recipe Servings',
    recipe_servings_hint: 'Number of portions in the original recipe — ingredients will be divided by this value so the calendar shows one serving per person.',
    err_no_servings: 'Enter the number of recipe servings (min. 1)',
    meal_type_required: 'required',
    matched_product_col: 'Matched product',
    recipe_not_found: (name) => `Recipe "${name}" not found`,
    del_selected_recipes: (n) => `Delete selected (${n})`,
    del_all_recipes: 'Delete all',
    select_label: 'Select',
    deselect_label: 'Deselect',
    confirm_del_selected_recipes: (n) => `Are you sure you want to delete ${n} selected recipes?`,
    confirm_del_all_recipes: (n) => `Are you sure you want to delete all ${n} recipes?`,
    del_selected_label: (n) => `Delete selected (${n})`,
    del_all_recipes_title: 'Delete all recipes',
    del_selected_recipes_title: 'Delete selected recipes',
    recipe_deleted: 'Recipe deleted',
    all_recipes_deleted: 'All recipes deleted',
    recipes_deleted: (n) => `Deleted ${n} recipes`,
    recipe_saved: 'Recipe added',
    add_ing_label: '+ Add ingredient',
    loading_ing: 'Loading ingredients…',
    del_ing_title: 'Delete ingredient',
    del_ing_confirm: (name) => `Remove "${name}" from the recipe?`,
    recipe_search_ph: 'Search recipe...',
    see_recipe: 'See recipe ↗',
    recipe_col_name: 'Name',
    recipe_col_kcalmacro: 'Kcal / Macro',
    recipe_col_meal: 'Meal',
    recipe_col_price: 'Price',
    plus_macro: '+ macro',
    price_input_ph: 'price',
    pkg_input_ph: 'pkg.',
    existing_product: 'existing product',
    shown_of: (shown, total, type) => `Showing ${shown} of ${total} ${type}…`,
    fav_add: 'Add to favourites',
    fav_remove: 'Remove from favourites',
    click_to_edit: 'Double-click to edit',
    click_change_meal: 'Click to change meal type',
    no_type: '+ type',
    no_type_label: '— none —',
    delete_confirm_recipe: (name) => `Are you sure you want to delete "${name}"?`,
    del_recipe_title: 'Delete recipe',
    save_changes_label: 'Changes saved',
    name_saved_label: 'Name saved',
    save_error_label: 'Save error',
    recipe_name_max: 'Recipe name max 200 characters',
    each_ing_has_product: 'Select a product for each ingredient',
    weight_range_error: 'Weight must be between 1 and 99999',
    category_error: 'Error saving category',
    select_meal_type: 'Select meal type (Breakfast / Lunch / Dinner / Snack / Dessert)',
    // Products extra
    search_products_hint: 'LOOKING FOR PRODUCTS?',
    product_paste_ph: 'Paste a product from the store website or type it in, e.g:\n\nBananas 1kg £3\n\nor paste the full product page text',
    price_ph: 'e.g. 3.49',
    pkg_ph: 'e.g. 1000',
    save_doc_step_pre: 'Save the document with the response as',
    csv_format_full: 'name,weight,unit,price',
    csv_format_short: 'name,price',
    opt1_s2_pre: 'Click', opt1_s2_suf: 'will extract products and prices',
    opt1_s3_pre: 'Check the matches and click',
    apply_ai_label: 'Apply with AI', apply_changes_label: 'Apply changes',
    apply_file_label: 'Apply file',
    opt2_required_fmt: 'Required format:', opt2_or: 'or:',
    opt2_manually: 'manually enter weight and unit',
    opt2_upload_pre: 'Upload the file and click',
    go_to_ai_pre: 'Go to', go_to_ai_suf: 'and paste the following prompt:',
    check_data_label: 'Check the data is correct:',
    price_per_kg_lbl: 'Price / kg',
    pkg_btn: 'In pkg.',
    weight_btn: 'By weight',
    pkg_capacity_lbl: 'Package capacity',
    quick_update_hint: 'Want to quickly fill in / update the product list?',
    go_to_hint: 'Go to',
    paste_products_step: 'Paste the product list / provide products',
    create_doc_step: 'Create a new text document',
    copy_response_step: 'Copy the response from Claude / Gemini / ChatGPT into the document',
    save_doc_step: (code) => `Save the document with the response as ${code}`,
    drag_doc_step: 'Then drag the saved document into the',
    products_prompt: `You are an assistant for formatting product lists. When I paste a list of products in any format, return ONLY a ready CSV in the format:\nname,weight,unit,price\nRules:\n- First line is always the header: name,weight,unit,price\n- weight = number (e.g. 1, 0.5, 200)\n- unit = kg / g / l / ml / pcs\n- price = number with a dot (e.g. 4.50)\n- If anything is missing: weight = 1, unit = pcs, price = 0.00\n- No comments -- only the CSV itself\n\nWaiting for my list.`,
    del_selected_products: (n) => `Delete selected (${n})`,
    del_all_products: 'Delete all',
    confirm_del_selected_products: (n) => `Are you sure you want to delete ${n} selected products?`,
    confirm_del_all_products: (n) => `Are you sure you want to delete all ${n} products? This cannot be undone.`,
    del_selected_products_title: 'Delete selected products',
    del_all_products_title: 'Delete all products',
    products_deleted: (n) => `Deleted ${n} products`,
    all_products_deleted: 'All products deleted',
    product_added: 'Product added',
    product_deleted: 'Product deleted',
    changes_saved: 'Changes saved',
    product_not_found: (name) => `Product "${name}" not found`,
    pkg_capacity_col: 'Package capacity',
    price_pkg_kg_col: 'Price (pkg/kg)',
    by_weight_label: 'By weight',
    price_kg_edit: 'Price/kg',
    price_op_edit: 'Price/pkg',
    get_macros_btn: 'Fetch macros',
    pkg_op_btn: 'In pkg.',
    shown_products: (shown, total) => `Showing ${shown} of ${total} products…`,
    product_exists_err: (name) => `Product "${name}" already exists`,
    product_adding: (name) => `Product "${name}" added — fetching macros...`,
    product_added_macro: (name, hasMacro) => `Product "${name}" added${hasMacro ? ' with macros' : ''}`,
    valid_price_err: 'Enter a valid price for the selected products',
    price_max_err: 'Price cannot exceed 99999',
    weight_max_err: 'Weight cannot exceed 99999',
    name_max_err: 'Product name max 200 characters',
    fill_name_err: 'Fill in the name for new products',
    save_products_err: 'Error saving products',
    del_during_err: 'Error during deletion',
    // Summary extra
    food_expenses_label: 'Food expenses',
    include_label: 'Include:',
    no_data_label: 'No data',
    total_label: 'Total',
    create_template_btn: '+ Create template',
    go_to_calendar_btn: 'Go to calendar',
    delete_template_btn: 'Delete',
    from_label: 'From',
    to_label: 'To',
    // Export extra
    week_preview: 'Week preview',
    loading_preview: 'Loading...',
    no_meals_preview: 'No meals planned',
    days_with_meals: (days, total) => `${days} ${days === 1 ? 'day' : 'days'} with meals · ${total} ${total === 1 ? 'meal' : 'meals'}`,
    shop_list_title: 'Shopping list',
    selected_days: (n) => `Selected: ${n} ${n === 1 ? 'day' : 'days'}`,
    include_profiles: 'Include profiles',
    export_recipe_search: 'Search recipe...',
    export_no_results: 'No results',
    export_do_export: 'Export ingredients',
    kogo_uwzgledniamy: 'Who to include',
    select_at_least_one_day: 'Select at least one day',
    export_macro_err: 'Fill in data in the Macro Calculator and save it before exporting.',
    export_macro_gen_err: 'Could not generate the card — check data in the calculator.',
    export_wydatki_err: 'Could not fetch expense data',
    export_calendar_err: 'Could not fetch calendar',
    export_shop_list_err: 'Could not generate shopping list',
    export_select_period: 'Select a period',
    export_select_recipe: 'Select a recipe',
    // MacroCalculator extra
    fill_left: 'Fill in data on the left',
    macro_goals_saved: 'Macro goals saved! Colours will appear in the calendar.',
    lost_receipt_hint: 'Lost your receipt? Open the receipt in the store app, take a screenshot and upload it',
    no_assignment_hint: 'No match — assign to a similar product or leave',
    new_product_opt: '➕ Create new product',
    create_new_option: (name) => `+ Create new: "${name}"`,
    // MemberPicker (sidebar — all tabs)
    member_added: (name) => `Added "${name}"`,
    err_member_add: 'Error adding member',
    member_renamed: 'Name changed',
    err_member_rename: 'Error renaming',
    member_delete_title: (name) => `Delete "${name}"`,
    member_delete_confirm: 'All planned meals for this person will be deleted. This cannot be undone.',
    member_deleted: (name) => `Deleted "${name}"`,
    err_member_delete: 'Error deleting',
    member_switch_hint: 'Click to switch · Double-click to rename',
    member_name_ph: 'Name...',
    member_add_person: 'Add person',
    // Products — confirmations
    delete_confirm_product: (name) => `Are you sure you want to delete "${name}"? This cannot be undone.`,
    // Calendar
    recipes_count: (n) => (n === 1 ? '1 recipe' : `${n} recipes`),
    click_edit_macro: 'Click to edit macros (values per 100g)',
    macro_day_label: 'Macro',
    cal_no_recipes_match: (q) => `No recipes matching "${q}"`,
    shown_recipes: (shown, total) => `Showing ${shown} of ${total} recipes…`,
    // MacroCalculator — placeholders
    placeholder_eg_age: 'e.g. 28',
    placeholder_eg_weight: 'e.g. 75',
    placeholder_eg_height: 'e.g. 178',
    // Login
    login_privacy_prefix: 'By creating an account you agree to the ',
    login_privacy_link: 'Privacy Policy',
    login_privacy_suffix: ' of Ontrack.',
    // Profile — account language change
    profile_lang_name_pl: '🇵🇱 Polski',
    profile_lang_name_en: '🇬🇧 English',
    profile_lang_desc: (name) => `Current account language: ${name}. This determines the language of default products and recipes.`,
    profile_lang_change_title: 'Change account language?',
    profile_lang_warning_label: 'Important:',
    profile_lang_warning_body: (from, to) => `The data you have in ${from} (products, recipes, meal plan) will not be available after switching to ${to}.`,
    profile_lang_warning_note: 'Your existing data will not be deleted — but it was created in the other language version and will not match the new defaults.',
    profile_lang_change_confirm: 'Change anyway',
    // Expenses — drinks period
    drinks_period_week: 'week (7 days)',
    drinks_period_month: (d) => `month (${d} days)`,
    drinks_period_custom: (d) => `selected period (${d} days)`,
    // Export — help and placeholders
    date_format_ph: 'dd/mm/yyyy',
    export_help_summary: 'Food expenses + fixed costs selected in the Expenses tab (rent, electricity, gas…), prorated by number of days.',
    export_help_macro: 'Export from the Macro Calculator — personal data, BMI, caloric needs and macro goals.',
    export_help_calendar: 'Meal plan printout. You can toggle kcal and macro visibility per day before printing.',
    export_help_ingredients: 'Search for a recipe by name, then export the ingredient list with quantities and prices ready to print.',
    export_help_shopping: 'Select days, product list from recipes calculated in packages. You can remove items before printing.',
    export_help_preview: 'Mini calendar view reacting to the selected period. Shows meals planned for each day.',
    eg_prefix: 'e.g.',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  const switchLang = (l) => {
    setLang(l);
    localStorage.setItem('lang', l);
  };

  const t = (key) => {
    const val = T[lang]?.[key];
    if (val !== undefined) return val;
    return T['pl']?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
