import React, { createContext, useContext, useState } from 'react';

const T = {
  pl: {
    // App/Nav
    loading: 'Ładowanie…',
    tab_calendar: 'Planer Posiłków',
    tab_recipes: 'Dodaj/Edytuj Listę przepisów',
    tab_products: 'Dodaj/Edytuj Listę produktów',
    tab_summary: 'Podsumowania Tygodnia/Miesiąca',
    logout: 'Wyloguj',
    profile: 'Profil',
    // Profile modal
    my_profile: 'Mój profil',
    delete_account: 'Usuń konto',
    delete_confirm: 'Czy na pewno chcesz usunąć swoje konto? Wszystkie dane zostaną trwale usunięte. Tej operacji nie można cofnąć.',
    close: 'Zamknij',
    deleting: 'Usuwanie…',
    // Login
    subtitle_login: 'Zaloguj się do swojego konta',
    subtitle_register: 'Utwórz nowe konto',
    google_btn: 'Kontynuuj przez Google',
    or: 'lub',
    password_lbl: 'HASŁO',
    password_ph: 'Min. 8 znaków',
    email_ph: 'twój@email.com',
    login_btn: 'Zaloguj się',
    register_btn: 'Zarejestruj się',
    no_account: 'Nie masz konta?',
    have_account: 'Masz już konto?',
    auth_error: 'Wystąpił błąd — spróbuj ponownie',
    // Calendar arrays
    slot_labels: ['Śniadanie', 'Drugie śniadanie', 'Obiad', 'Podwieczorek', 'Kolacja'],
    month_names: ['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'],
    day_short: ['Pon','Wt','Śr','Czw','Pt','Sob','Niedz'],
    day_full: ['Poniedziałek','Wtorek','Środa','Czwartek','Piątek','Sobota','Niedziela'],
    // Calendar UI
    how_to_title: 'Jak korzystać z kalendarza?',
    expand: 'Rozwiń',
    collapse: 'Zwiń',
    tpl_title: 'Tworzenie szablonów posiłków na tydzień',
    your_tpls: 'Twoje szablony',
    tpl_drag_hint: 'Przeciągnij przepisy z karuzeli na dni tygodnia, następnie zapisz jako szablon.',
    tpl_name_ph: 'Nazwa szablonu (np. Tydzień fit)',
    save_tpl: 'Zapisz szablon',
    clear: 'Wyczyść',
    no_tpls: 'Brak zapisanych szablonów — utwórz pierwszy powyżej.',
    apply_from_mon: 'Zastosuj od poniedziałku:',
    apply: 'Zastosuj',
    meals_count: (n) => `${n} posiłków`,
    carousel_title: 'Przepisy',
    drag_to_cal: 'Przeciągnij na dzień w kalendarzu lub na szablon poniżej',
    no_recipes_cal: 'Brak przepisów',
    err_load_recipes: 'Błąd ładowania przepisów',
    err_load_plan: 'Błąd ładowania planu',
    err_del_meal: 'Błąd usuwania posiłku',
    err_del_meals: 'Błąd usuwania posiłków',
    err_del_week: 'Błąd usuwania tygodnia',
    err_paste_day: 'Błąd wklejania dnia',
    err_paste_week: 'Błąd wklejania tygodnia',
    err_copy_day: 'Błąd kopiowania dnia',
    err_add_meal: 'Błąd dodawania posiłku',
    err_move_meal: 'Błąd przenoszenia posiłku',
    confirm_del_day: (n, d) => `Usunąć wszystkie ${n} posiłki z ${d}?`,
    confirm_del_week: (n) => `Usunąć wszystkie ${n} posiłki z tego tygodnia?`,
    toast_copy_day: (d) => `⧉ Skopiowano dzień ${d}`,
    toast_copy_week: '⧉ Tydzień skopiowany do schowka i edytora szablonu',
    clipboard_day: (d) => `Schowek: dzień ${d}`,
    clipboard_week: (d) => `Schowek: tydzień od ${d}`,
    clear_clipboard: '✕ wyczyść',
    paste_day_hint: 'kliknij ⎘ na innym dniu żeby wkleić',
    paste_week_hint: 'kliknij ⎘ przy innym tygodniu żeby wkleić',
    drag_day_title: 'Przeciągnij dzień',
    copy_day_title: 'Kopiuj dzień',
    paste_day_title: 'Wklej dzień',
    del_day_title: 'Usuń wszystkie posiłki tego dnia',
    copy_week_title: 'Kopiuj tydzień / załaduj do szablonu',
    paste_week_title: 'Wklej tydzień',
    del_week_title: 'Usuń cały tydzień',
    ht_meals_title: '🍽️ Planowanie posiłków',
    ht_meals_1: 'Chwyć przepis z karuzeli i przeciągnij na slot w dniu (5 slotów: śniadanie–kolacja)',
    ht_meals_2: 'Posiłek możesz przesunąć między dniami chwytając go za nazwę',
    ht_meals_3: 'Kliknij ✕ przy posiłku żeby go usunąć, lub 🗑 w nagłówku dnia żeby wyczyścić cały dzień',
    ht_copy_title: '📋 Kopiowanie dni i tygodni',
    ht_copy_1: '⧉ w nagłówku dnia — kopiuje dzień do schowka',
    ht_copy_2: '⎘ — wkleja schowek na inny dzień',
    ht_copy_3: '⠿ przy numerze dnia — chwyć i przeciągnij dzień na inny dzień',
    ht_copy_4: '⧉ / ⎘ / 🗑 po lewej każdego wiersza — kopiuj, wklej lub usuń cały tydzień',
    ht_tpl_title: '📁 Szablony tygodnia',
    ht_tpl_1: 'Kliknij ⧉ przy tygodniu — załaduje posiłki do edytora szablonu poniżej',
    ht_tpl_2: 'W edytorze przeciągaj przepisy z karuzeli na dni tygodnia',
    ht_tpl_3: 'Wpisz nazwę i kliknij Zapisz szablon',
    ht_tpl_4: 'Szablon możesz zastosować na dowolny przyszły tydzień',
    // Recipes
    add_recipe_title: 'Dodaj przepis',
    how_to_recipe: 'Jak dodać przepis?',
    format_title: 'Format tekstu:',
    fmt_1: 'Pierwsza linia — nazwa przepisu',
    fmt_2: 'Każdy składnik w osobnej linii',
    fmt_3: 'Podaj nazwę składnika i ilość z jednostką (g, ml, kg, l, łyżka, łyżeczka, szklanka…)',
    fmt_4: 'Możesz wkleić tekst ze strony z przepisem',
    ai_tip: '✨ Parsuj AI — Gemini rozumie każdy format, polską gramatykę i kontekst.',
    regex_tip: '🔍 Parsuj regex — szybkie, lokalne, bez limitu. Wymaga podania ilości w tekście.',
    daily_limit: 'Limit: 2 dziennie.',
    example: 'Przykład:',
    remaining_ai: (n) => `Pozostało dziś parsowań AI: ${n}`,
    recipe_ph: 'Wklej lub wpisz przepis...\n\nNazwa przepisu\nSkładnik 1 - ilość\nSkładnik 2 - ilość',
    parse_ai_btn: '✨ Parsuj przez AI',
    parsing_ai: '⏳ Gemini analizuje...',
    parse_regex_btn: '🔍 Parsuj bez AI',
    recipe_name_lbl: 'Nazwa przepisu',
    ingredients_lbl: (m, total) => `Składniki — ${m}/${total} dopasowanych`,
    save_recipe: 'Zapisz przepis',
    back: '← Wróć',
    original_text_lbl: 'Oryginalny tekst przepisu — porównaj i ręcznie dołóż brakujące składniki',
    recipe_list_title: 'Lista przepisów',
    no_recipes_add: 'Brak przepisów — dodaj pierwszy!',
    col_product: 'Produkt',
    col_weight: 'Gramatura',
    col_cost: 'Koszt',
    info_section: 'ℹ️ Info',
    edit_notes: 'Edytuj',
    save_notes: 'Zapisz',
    cancel: 'Anuluj',
    no_notes: 'Brak notatek — kliknij Edytuj żeby dodać.',
    no_match_opt: '— brak dopasowania —',
    err_save_recipe: 'Błąd zapisywania przepisu',
    err_save_notes: 'Błąd zapisywania notatki',
    err_no_name: 'Brak nazwy przepisu',
    err_no_ingredients: 'Żaden składnik nie ma dopasowanego produktu',
    err_parse_regex: 'Nie udało się wyłapać składników — sprawdź format',
    confirm_del_recipe: 'Usunąć przepis?',
    show_ingredients: 'Składniki',
    hide_ingredients: 'Zwiń',
    delete: 'Usuń',
    err_load_recipes_list: 'Błąd ładowania przepisów',
    // Products
    add_product_title: 'Dodaj produkt',
    basic_info: 'Podstawowe informacje',
    product_name_lbl: 'Nazwa produktu',
    product_name_ph: 'np. Jogurt naturalny',
    pkg_qty_lbl: 'Ilość w opakowaniu',
    unit_lbl: 'Jednostka',
    price_section: 'Cena',
    pkg_price_lbl: 'Cena opakowania (zł)',
    pkg_price_ph: 'np. 3.49',
    macro_auto_title: '✨ Makro i Kalorie — automatycznie',
    macro_auto_desc: 'Po dodaniu produktu system pobierze wartości Kcal, Białka, Tłuszczów i Węglowodanów automatycznie z bazy Open Food Facts.',
    macro_edit_hint: 'Chcesz je zmienić? Kliknij Edytuj przy produkcie na liście poniżej.',
    add_product_btn: 'Dodaj produkt',
    import_title: 'Importuj ceny z paragonu lub pliku CSV / TXT',
    import_how_to: 'Jak korzystać z importu?',
    opt1_title: 'Opcja 1: Zdjęcie paragonu',
    opt1_s1: 'Wgraj zdjęcie JPG, PNG lub WEBP',
    opt1_s2: 'Kliknij Zastosuj AI — Gemini wyciągnie produkty i ceny',
    opt1_s3: 'Sprawdź dopasowania i kliknij Zastosuj',
    ai_daily_lim: '⚠️ Limit: 2 importy AI dziennie.',
    ai_rem: (n) => ` Pozostało: ${n}.`,
    opt2_title: 'Opcja 2: Plik CSV / TXT',
    opt2_fmt: 'Format:',
    opt2_s2: 'Wgraj plik i kliknij Zastosuj plik',
    no_lim: '✓ Bez limitu, bez AI.',
    click_drag_file: 'Kliknij lub przeciągnij plik',
    file_types_hint: 'Opcja 1: JPG, PNG, WEBP — paragon (AI) | Opcja 2: TXT, CSV — cennik (darmowe)',
    click_change: 'Kliknij żeby wybrać inny plik',
    apply_ai_btn: '✨ Zastosuj przez AI (Gemini)',
    analyzing: '⏳ Gemini analizuje...',
    apply_file_btn: '📄 Zastosuj plik (darmowe)',
    processing: '⏳ Przetwarzam...',
    check_prices: 'Zaznacz produkty, sprawdź ceny i kliknij Zastosuj.',
    col_from_receipt: 'Z paragonu',
    col_qty: 'Ilość',
    col_pkg_price: 'Cena opak.',
    col_matched: 'Dopasowany produkt',
    col_new_price: 'Nowa cena',
    no_match_prod: 'Brak dopasowania',
    apply_changes: 'Zastosuj zmiany',
    product_list_title: 'Lista produktów',
    col_name: 'Nazwa',
    col_kcal: 'Kcal/100g',
    col_macro: 'Makro / 100g',
    col_price: 'Cena',
    edit_btn: 'Edytuj',
    save_btn: 'Zapisz',
    del_btn: 'Usuń',
    confirm_del_product: 'Usunąć produkt?',
    no_products: 'Brak produktów',
    fetching_macro: '⏳ Pobieranie Makro i Kalorii z Open Food Facts…',
    kcal_lbl: 'Kalorie (kcal/100g)',
    protein_lbl: 'Białko (g/100g)',
    fat_lbl: 'Tłuszcze (g/100g)',
    carbs_lbl: 'Węglowodany (g/100g)',
    auto_fill: '✨ Auto Uzupełnij',
    price_tip: (unit) => {
      const u = unit === 'szt' ? 'szt' : unit === 'ml' ? '100ml' : '100g';
      return `💡 Cena: wpisz ilość w opakowaniu i cenę za całe opakowanie — system przeliczy na zł/${u}.`;
    },
    auto_fill_tip: '✨ Auto Uzupełnij — pobiera Kcal i Makro automatycznie z bazy Open Food Facts na podstawie nazwy produktu.',
    err_fill_fields: 'Wypełnij wszystkie pola',
    err_not_found_off: (name) => `Nie znaleziono danych dla "${name}" — uzupełnij ręcznie`,
    err_off: 'Błąd połączenia z Open Food Facts',
    err_load_products: 'Błąd ładowania produktów',
    macro_updated_suffix: ' · Makro zaktualizowane automatycznie.',
    at_least_one: 'Zaznacz przynajmniej jeden produkt',
    // Summary
    summary_title: '📊 Podsumowanie zakupów',
    date_from: 'Od',
    date_to: 'Do',
    generate: 'Generuj',
    generating: 'Ładowanie...',
    shopping_list_title: 'Lista zakupów',
    col_total_weight: 'Łączna gramatura',
    col_exact_pkgs: 'Opakowania (dokładnie)',
    col_buy_pkgs: 'Opakowania (do kupienia)',
    col_price_per_pkg: 'Cena/opak.',
    col_total_cost: 'Koszt całkowity',
    summary_period: (s, e) => `Okres: ${s} — ${e}`,
    summary_prod_count: (n) => `Liczba produktów: ${n}`,
    total_cost_lbl: 'Łączny koszt zakupów',
    no_meals_range: 'Brak zaplanowanych posiłków w wybranym okresie',
    err_load_summary: 'Błąd ładowania podsumowania',
    err_select_range: 'Wybierz zakres dat',
    err_date_order: 'Data początkowa nie może być późniejsza niż końcowa',
  },
  en: {
    // App/Nav
    loading: 'Loading…',
    tab_calendar: 'Meal Planner',
    tab_recipes: 'Add/Edit Recipe List',
    tab_products: 'Add/Edit Product List',
    tab_summary: 'Weekly/Monthly Summaries',
    logout: 'Log out',
    profile: 'Profile',
    // Profile modal
    my_profile: 'My Profile',
    delete_account: 'Delete account',
    delete_confirm: 'Are you sure you want to delete your account? All data will be permanently deleted. This action cannot be undone.',
    close: 'Close',
    deleting: 'Deleting…',
    // Login
    subtitle_login: 'Sign in to your account',
    subtitle_register: 'Create a new account',
    google_btn: 'Continue with Google',
    or: 'or',
    password_lbl: 'PASSWORD',
    password_ph: 'Min. 8 characters',
    email_ph: 'your@email.com',
    login_btn: 'Sign in',
    register_btn: 'Register',
    no_account: "Don't have an account?",
    have_account: 'Already have an account?',
    auth_error: 'An error occurred — please try again',
    // Calendar arrays
    slot_labels: ['Breakfast', 'Second breakfast', 'Lunch', 'Afternoon snack', 'Dinner'],
    month_names: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    day_short: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    day_full: ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
    // Calendar UI
    how_to_title: 'How to use the calendar?',
    expand: 'Expand',
    collapse: 'Collapse',
    tpl_title: 'Creating weekly meal templates',
    your_tpls: 'Your templates',
    tpl_drag_hint: 'Drag recipes from the carousel to days of the week, then save as a template.',
    tpl_name_ph: 'Template name (e.g. Fit Week)',
    save_tpl: 'Save template',
    clear: 'Clear',
    no_tpls: 'No saved templates — create the first one above.',
    apply_from_mon: 'Apply from Monday:',
    apply: 'Apply',
    meals_count: (n) => `${n} meals`,
    carousel_title: 'Recipes',
    drag_to_cal: 'Drag to a day in the calendar or to a template below',
    no_recipes_cal: 'No recipes',
    err_load_recipes: 'Error loading recipes',
    err_load_plan: 'Error loading plan',
    err_del_meal: 'Error deleting meal',
    err_del_meals: 'Error deleting meals',
    err_del_week: 'Error deleting week',
    err_paste_day: 'Error pasting day',
    err_paste_week: 'Error pasting week',
    err_copy_day: 'Error copying day',
    err_add_meal: 'Error adding meal',
    err_move_meal: 'Error moving meal',
    confirm_del_day: (n, d) => `Delete all ${n} meals from ${d}?`,
    confirm_del_week: (n) => `Delete all ${n} meals from this week?`,
    toast_copy_day: (d) => `⧉ Day ${d} copied`,
    toast_copy_week: '⧉ Week copied to clipboard and template editor',
    clipboard_day: (d) => `Clipboard: day ${d}`,
    clipboard_week: (d) => `Clipboard: week from ${d}`,
    clear_clipboard: '✕ clear',
    paste_day_hint: 'click ⎘ on another day to paste',
    paste_week_hint: 'click ⎘ next to another week to paste',
    drag_day_title: 'Drag day',
    copy_day_title: 'Copy day',
    paste_day_title: 'Paste day',
    del_day_title: 'Delete all meals for this day',
    copy_week_title: 'Copy week / load into template',
    paste_week_title: 'Paste week',
    del_week_title: 'Delete entire week',
    ht_meals_title: '🍽️ Meal planning',
    ht_meals_1: 'Grab a recipe from the carousel and drag it to a slot in a day (5 slots: breakfast–dinner)',
    ht_meals_2: 'You can move a meal between days by dragging it by name',
    ht_meals_3: 'Click ✕ next to a meal to remove it, or 🗑 in the day header to clear the whole day',
    ht_copy_title: '📋 Copying days and weeks',
    ht_copy_1: '⧉ in the day header — copies the day to clipboard',
    ht_copy_2: '⎘ — pastes the clipboard to another day',
    ht_copy_3: '⠿ next to the day number — grab and drag a day to another day',
    ht_copy_4: '⧉ / ⎘ / 🗑 on the left of each row — copy, paste or delete an entire week',
    ht_tpl_title: '📁 Week templates',
    ht_tpl_1: 'Click ⧉ next to a week — loads meals into the template editor below',
    ht_tpl_2: 'In the editor, drag recipes from the carousel to days of the week',
    ht_tpl_3: 'Enter a name and click Save template',
    ht_tpl_4: 'You can apply the template to any future week',
    // Recipes
    add_recipe_title: 'Add recipe',
    how_to_recipe: 'How to add a recipe?',
    format_title: 'Text format:',
    fmt_1: 'First line — recipe name',
    fmt_2: 'Each ingredient on a separate line',
    fmt_3: 'Provide the ingredient name and amount with unit (g, ml, kg, l, tablespoon, teaspoon, cup…)',
    fmt_4: 'You can paste text from a recipe website',
    ai_tip: '✨ AI Parse — Gemini understands any format, grammar, and context.',
    regex_tip: '🔍 Regex parse — fast, local, no limit. Requires amounts in the text.',
    daily_limit: 'Limit: 2 per day.',
    example: 'Example:',
    remaining_ai: (n) => `AI parses remaining today: ${n}`,
    recipe_ph: 'Paste or type a recipe...\n\nRecipe name\nIngredient 1 - amount\nIngredient 2 - amount',
    parse_ai_btn: '✨ Parse with AI',
    parsing_ai: '⏳ Gemini is analysing...',
    parse_regex_btn: '🔍 Parse without AI',
    recipe_name_lbl: 'Recipe name',
    ingredients_lbl: (m, total) => `Ingredients — ${m}/${total} matched`,
    save_recipe: 'Save recipe',
    back: '← Back',
    original_text_lbl: 'Original recipe text — compare and manually add missing ingredients',
    recipe_list_title: 'Recipe list',
    no_recipes_add: 'No recipes — add the first one!',
    col_product: 'Product',
    col_weight: 'Weight',
    col_cost: 'Cost',
    info_section: 'ℹ️ Info',
    edit_notes: 'Edit',
    save_notes: 'Save',
    cancel: 'Cancel',
    no_notes: 'No notes — click Edit to add.',
    no_match_opt: '— no match —',
    err_save_recipe: 'Error saving recipe',
    err_save_notes: 'Error saving note',
    err_no_name: 'Recipe name is required',
    err_no_ingredients: 'No ingredient has a matched product',
    err_parse_regex: 'Could not extract ingredients — check the format',
    confirm_del_recipe: 'Delete recipe?',
    show_ingredients: 'Ingredients',
    hide_ingredients: 'Collapse',
    delete: 'Delete',
    err_load_recipes_list: 'Error loading recipes',
    // Products
    add_product_title: 'Add product',
    basic_info: 'Basic information',
    product_name_lbl: 'Product name',
    product_name_ph: 'e.g. Natural yogurt',
    pkg_qty_lbl: 'Package quantity',
    unit_lbl: 'Unit',
    price_section: 'Price',
    pkg_price_lbl: 'Package price (zł)',
    pkg_price_ph: 'e.g. 3.49',
    macro_auto_title: '✨ Macros & Calories — automatically',
    macro_auto_desc: 'After adding the product the system will automatically fetch Kcal, Protein, Fat and Carbohydrate values from Open Food Facts.',
    macro_edit_hint: 'Want to change them? Click Edit next to the product in the list below.',
    add_product_btn: 'Add product',
    import_title: 'Import prices from a receipt or CSV / TXT file',
    import_how_to: 'How to use import?',
    opt1_title: 'Option 1: Receipt photo',
    opt1_s1: 'Upload a JPG, PNG or WEBP photo',
    opt1_s2: 'Click Apply AI — Gemini will extract products and prices',
    opt1_s3: 'Check the matches and click Apply',
    ai_daily_lim: '⚠️ Limit: 2 AI imports per day.',
    ai_rem: (n) => ` Remaining: ${n}.`,
    opt2_title: 'Option 2: CSV / TXT file',
    opt2_fmt: 'Format:',
    opt2_s2: 'Upload the file and click Apply file',
    no_lim: '✓ No limit, no AI.',
    click_drag_file: 'Click or drag a file',
    file_types_hint: 'Option 1: JPG, PNG, WEBP — receipt (AI) | Option 2: TXT, CSV — price list (free)',
    click_change: 'Click to choose a different file',
    apply_ai_btn: '✨ Apply with AI (Gemini)',
    analyzing: '⏳ Gemini is analysing...',
    apply_file_btn: '📄 Apply file (free)',
    processing: '⏳ Processing...',
    check_prices: 'Select products, check prices and click Apply.',
    col_from_receipt: 'From receipt',
    col_qty: 'Qty',
    col_pkg_price: 'Pkg price',
    col_matched: 'Matched product',
    col_new_price: 'New price',
    no_match_prod: 'No match',
    apply_changes: 'Apply changes',
    product_list_title: 'Product list',
    col_name: 'Name',
    col_kcal: 'Kcal/100g',
    col_macro: 'Macro / 100g',
    col_price: 'Price',
    edit_btn: 'Edit',
    save_btn: 'Save',
    del_btn: 'Delete',
    confirm_del_product: 'Delete product?',
    no_products: 'No products',
    fetching_macro: '⏳ Fetching Macros and Calories from Open Food Facts…',
    kcal_lbl: 'Calories (kcal/100g)',
    protein_lbl: 'Protein (g/100g)',
    fat_lbl: 'Fat (g/100g)',
    carbs_lbl: 'Carbohydrates (g/100g)',
    auto_fill: '✨ Auto Fill',
    price_tip: (unit) => {
      const u = unit === 'szt' ? 'pc' : unit === 'ml' ? '100ml' : '100g';
      return `💡 Price: enter the package quantity and total price — the system will calculate zł/${u}.`;
    },
    auto_fill_tip: '✨ Auto Fill — fetches Kcal and Macros from Open Food Facts based on the product name.',
    err_fill_fields: 'Fill in all fields',
    err_not_found_off: (name) => `No data found for "${name}" — fill in manually`,
    err_off: 'Error connecting to Open Food Facts',
    err_load_products: 'Error loading products',
    macro_updated_suffix: ' · Macros updated automatically.',
    at_least_one: 'Select at least one product',
    // Summary
    summary_title: '📊 Shopping summary',
    date_from: 'From',
    date_to: 'To',
    generate: 'Generate',
    generating: 'Loading...',
    shopping_list_title: 'Shopping list',
    col_total_weight: 'Total weight',
    col_exact_pkgs: 'Packages (exact)',
    col_buy_pkgs: 'Packages (to buy)',
    col_price_per_pkg: 'Price/pkg',
    col_total_cost: 'Total cost',
    summary_period: (s, e) => `Period: ${s} — ${e}`,
    summary_prod_count: (n) => `Products: ${n}`,
    total_cost_lbl: 'Total shopping cost',
    no_meals_range: 'No meals planned in the selected period',
    err_load_summary: 'Error loading summary',
    err_select_range: 'Select a date range',
    err_date_order: 'Start date cannot be later than end date',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'pl');

  const switchLang = (l) => {
    setLang(l);
    localStorage.setItem('lang', l);
  };

  const t = (key) => {
    const val = T[lang]?.[key];
    if (val !== undefined) return val;
    return T['pl']?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
