"""API contract ID registry — must match docs/backend-migration/API_CONTRACT.md summary table."""

from __future__ import annotations

# Every row in the API_CONTRACT summary table (A01–H01).
CONTRACT_IDS: frozenset[str] = frozenset(
    {
        "A01",
        "A02",
        "A03",
        "A04",
        "A05",
        "A06",
        "A07",
        "A08",
        "A09",
        "M01",
        "M02",
        "M03",
        "M04",
        "M05",
        "P01",
        "P02",
        "P03",
        "P04",
        "P05",
        "P06",
        "R01",
        "R02",
        "R03",
        "R04",
        "R05",
        "R06",
        "R07",
        "R08",
        "R09",
        "MP01",
        "MP02",
        "MP03",
        "MP04",
        "MP05",
        "MP06",
        "DS01",
        "DS02",
        "DS03",
        "DS04",
        "DS05",
        "DS06",
        "N01",
        "I01",
        "I02",
        "I03",
        "F01",
        "PU01",
        "H01",
        "H02",
        "H03",
    }
)

# Maps contract ID → contract test module(s) that exercise the endpoint.
CONTRACT_COVERAGE: dict[str, tuple[str, ...]] = {
    "A01": ("test_auth_contract.py",),
    "A02": ("test_auth_contract.py",),
    "A03": ("test_auth_contract.py",),
    "A04": ("test_auth_contract.py",),
    "A05": ("test_auth_contract.py", "test_ui_locale_market.py"),
    "A09": ("test_ui_locale_market.py",),
    "A06": ("test_auth_contract.py",),
    "A07": ("test_auth_contract.py",),
    "A08": ("test_auth_contract.py",),
    "M01": ("test_members_contract.py",),
    "M02": ("test_members_contract.py",),
    "M03": ("test_members_contract.py",),
    "M04": ("test_members_contract.py",),
    "M05": ("test_members_contract.py",),
    "P01": ("test_products_contract.py",),
    "P02": ("test_products_contract.py",),
    "P03": ("test_products_contract.py",),
    "P04": ("test_products_contract.py",),
    "P05": ("test_products_contract.py",),
    "P06": ("test_products_contract.py",),
    "R01": ("test_recipes_contract.py",),
    "R02": ("test_recipes_contract.py",),
    "R03": ("test_recipes_contract.py",),
    "R04": ("test_recipes_contract.py",),
    "R05": ("test_recipes_contract.py",),
    "R06": ("test_recipes_contract.py",),
    "R07": ("test_recipes_contract.py",),
    "R08": ("test_recipes_contract.py",),
    "R09": ("test_recipes_contract.py",),
    "MP01": ("test_meal_plan_contract.py",),
    "MP02": ("test_meal_plan_contract.py",),
    "MP03": ("test_meal_plan_contract.py",),
    "MP04": ("test_meal_plan_contract.py",),
    "MP05": ("test_meal_plan_contract.py",),
    "MP06": ("test_meal_plan_contract.py",),
    "DS01": ("test_day_schedule_contract.py",),
    "DS02": ("test_day_schedule_contract.py",),
    "DS03": ("test_day_schedule_contract.py",),
    "DS04": ("test_day_schedule_contract.py",),
    "DS05": ("test_day_schedule_contract.py",),
    "DS06": ("test_day_schedule_contract.py",),
    "N01": ("test_nutrition_contract.py",),
    "I01": ("test_import_contract.py",),
    "I02": ("test_import_contract.py",),
    "I03": ("test_import_contract.py",),
    "F01": ("test_fuel_contract.py",),
    "PU01": ("test_public_dish_compare_http.py",),
    "H01": ("test_health_contract.py",),
    "H02": ("test_health_contract.py",),
    "H03": ("test_health_contract.py",),
}
